
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Katrin.Services.Metadata
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
public partial class ColumnMapping
{

	[DataMember]
    public System.Guid ColumnMappingId { get; set; }

	[DataMember]
    public string SourceEntityName { get; set; }

	[DataMember]
    public string SourceAttributeName { get; set; }

	[DataMember]
    public string TargetEntityName { get; set; }

	[DataMember]
    public string TargetAttributeName { get; set; }

	[DataMember]
    public Nullable<System.Guid> ImportMapId { get; set; }



	[DataMember]
    public virtual ImportMap ImportMap { get; set; }

}

}
