
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Katrin.Services.Metadata
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
public partial class EntityAttribute
{

    public EntityAttribute()
    {

        this.AttributeLookupValues = new HashSet<AttributeLookupValue>();

        this.CriteriaNodes = new HashSet<CriteriaNode>();

        this.NotificationRecipientAttributes = new HashSet<NotificationRecipientAttribute>();

        this.NotificationVariables = new HashSet<NotificationVariable>();

    }


	[DataMember]
    public System.Guid AttributeId { get; set; }

	[DataMember]
    public Nullable<System.Guid> AttributeTypeId { get; set; }

	[DataMember]
    public string LogicalType { get; set; }

	[DataMember]
    public string Name { get; set; }

	[DataMember]
    public string PhysicalName { get; set; }

	[DataMember]
    public Nullable<int> Length { get; set; }

	[DataMember]
    public Nullable<bool> IsNullable { get; set; }

	[DataMember]
    public System.Guid EntityId { get; set; }

	[DataMember]
    public string DefaultValue { get; set; }

	[DataMember]
    public int ColumnNumber { get; set; }

	[DataMember]
    public string LogicalName { get; set; }

	[DataMember]
    public byte[] VersionNumber { get; set; }

	[DataMember]
    public Nullable<int> MaxLength { get; set; }

	[DataMember]
    public Nullable<double> MinValue { get; set; }

	[DataMember]
    public Nullable<double> MaxValue { get; set; }

	[DataMember]
    public bool IsAuditEnabled { get; set; }

	[DataMember]
    public string TableColumnName { get; set; }

	[DataMember]
    public Nullable<System.Guid> OptionSetId { get; set; }

	[DataMember]
    public Nullable<int> AppDefaultValue { get; set; }

	[DataMember]
    public Nullable<bool> IsPKAttribute { get; set; }

	[DataMember]
    public Nullable<bool> IsCopyEnabled { get; set; }



	[DataMember]
    public virtual AttributeType AttributeType { get; set; }

	[DataMember]
    public virtual Entity Entity { get; set; }

	[DataMember]
    public virtual OptionSet OptionSet { get; set; }

	[DataMember]
    public virtual ICollection<AttributeLookupValue> AttributeLookupValues { get; set; }

	[DataMember]
    public virtual ICollection<CriteriaNode> CriteriaNodes { get; set; }

	[DataMember]
    public virtual ICollection<NotificationRecipientAttribute> NotificationRecipientAttributes { get; set; }

	[DataMember]
    public virtual ICollection<NotificationVariable> NotificationVariables { get; set; }

}

}
