
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Katrin.Services.Metadata
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
public partial class Entity
{

    public Entity()
    {

        this.Attributes = new HashSet<EntityAttribute>();

        this.RelationshipRoles = new HashSet<EntityRelationshipRole>();

        this.NotificationRecipientAttributes = new HashSet<NotificationRecipientAttribute>();

        this.NotificationVariables = new HashSet<NotificationVariable>();

    }


	[DataMember]
    public System.Guid EntityId { get; set; }

	[DataMember]
    public string Name { get; set; }

	[DataMember]
    public string PhysicalName { get; set; }

	[DataMember]
    public string LogicalName { get; set; }

	[DataMember]
    public string TableName { get; set; }

	[DataMember]
    public bool IsAuditEnabled { get; set; }



	[DataMember]
    public virtual ICollection<EntityAttribute> Attributes { get; set; }

	[DataMember]
    public virtual ICollection<EntityRelationshipRole> RelationshipRoles { get; set; }

	[DataMember]
    public virtual ICollection<NotificationRecipientAttribute> NotificationRecipientAttributes { get; set; }

	[DataMember]
    public virtual ICollection<NotificationVariable> NotificationVariables { get; set; }

}

}
