
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Katrin.Services.Metadata
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
public partial class EntityRelationship
{

    public EntityRelationship()
    {

        this.EntityRelationshipRelationships = new HashSet<EntityRelationshipRelationships>();

        this.EntityRelationshipRoles = new HashSet<EntityRelationshipRole>();

    }


	[DataMember]
    public System.Guid EntityRelationshipId { get; set; }

	[DataMember]
    public string SchemaName { get; set; }

	[DataMember]
    public byte EntityRelationshipType { get; set; }

	[DataMember]
    public bool IsCustomRelationship { get; set; }

	[DataMember]
    public bool IsCustomizable { get; set; }

	[DataMember]
    public byte[] VersionNumber { get; set; }



	[DataMember]
    public virtual ICollection<EntityRelationshipRelationships> EntityRelationshipRelationships { get; set; }

	[DataMember]
    public virtual ICollection<EntityRelationshipRole> EntityRelationshipRoles { get; set; }

}

}
