
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Katrin.Services.Metadata
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
public partial class NotificationVariable
{

    public NotificationVariable()
    {

        this.ProfileVariables = new HashSet<ProfileVariable>();

    }


	[DataMember]
    public System.Guid NotificationVariableId { get; set; }

	[DataMember]
    public Nullable<System.Guid> ParentId { get; set; }

	[DataMember]
    public Nullable<System.Guid> RelatedAttributeId { get; set; }

	[DataMember]
    public string Name { get; set; }

	[DataMember]
    public Nullable<System.Guid> EntityId { get; set; }

	[DataMember]
    public string NotificationUrl { get; set; }



	[DataMember]
    public virtual EntityAttribute Metadata_Attribute { get; set; }

	[DataMember]
    public virtual Entity Metadata_Entity { get; set; }

	[DataMember]
    public virtual ICollection<ProfileVariable> ProfileVariables { get; set; }

}

}
