
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Katrin.Services.Metadata
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
public partial class NotificationRecipientAttribute
{

	[DataMember]
    public System.Guid NotificationRecipientAttributeId { get; set; }

	[DataMember]
    public Nullable<System.Guid> RecipientEntityId { get; set; }

	[DataMember]
    public Nullable<System.Guid> AttributeId { get; set; }

	[DataMember]
    public Nullable<System.Guid> NotificationProfileId { get; set; }

	[DataMember]
    public Nullable<System.Guid> CriteriaId { get; set; }



	[DataMember]
    public virtual Criterion Criterion { get; set; }

	[DataMember]
    public virtual EntityAttribute Metadata_Attribute { get; set; }

	[DataMember]
    public virtual Entity Metadata_Entity { get; set; }

	[DataMember]
    public virtual NotificationProfile NotificationProfile { get; set; }

}

}
