
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Katrin.Services.Metadata
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
public partial class NotificationProfile
{

    public NotificationProfile()
    {

        this.NotificationRecipientAttributes = new HashSet<NotificationRecipientAttribute>();

        this.ProfileVariables = new HashSet<ProfileVariable>();

        this.Subscriptions = new HashSet<Subscription>();

    }


	[DataMember]
    public System.Guid NotificationProfileId { get; set; }

	[DataMember]
    public Nullable<System.Guid> CriteriaId { get; set; }

	[DataMember]
    public Nullable<System.Guid> NotificationTemplateId { get; set; }

	[DataMember]
    public Nullable<bool> IsSys { get; set; }

	[DataMember]
    public Nullable<System.Guid> SubjectTemplateId { get; set; }



	[DataMember]
    public virtual Criterion Criterion { get; set; }

	[DataMember]
    public virtual NotificationTemplate NotificationTemplate { get; set; }

	[DataMember]
    public virtual ICollection<NotificationRecipientAttribute> NotificationRecipientAttributes { get; set; }

	[DataMember]
    public virtual ICollection<ProfileVariable> ProfileVariables { get; set; }

	[DataMember]
    public virtual NotificationTemplate SubjectNotificationTemplate { get; set; }

	[DataMember]
    public virtual ICollection<Subscription> Subscriptions { get; set; }

}

}
