
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Katrin.Services.Metadata
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
public partial class NotificationTemplate
{

    public NotificationTemplate()
    {

        this.NotificationProfiles = new HashSet<NotificationProfile>();

        this.NotificationProfiles1 = new HashSet<NotificationProfile>();

    }


	[DataMember]
    public System.Guid NotificationTemplateId { get; set; }

	[DataMember]
    public string SubjectTemplate { get; set; }



	[DataMember]
    public virtual ICollection<NotificationProfile> NotificationProfiles { get; set; }

	[DataMember]
    public virtual ICollection<NotificationProfile> NotificationProfiles1 { get; set; }

}

}
