
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Katrin.Services.Metadata
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
public partial class SavedQuery
{

	[DataMember]
    public System.Guid SavedQueryId { get; set; }

	[DataMember]
    public string Name { get; set; }

	[DataMember]
    public string Description { get; set; }

	[DataMember]
    public int QueryType { get; set; }

	[DataMember]
    public bool IsDefault { get; set; }

	[DataMember]
    public System.Guid ReturnedTypeId { get; set; }

	[DataMember]
    public Nullable<bool> IsUserDefined { get; set; }

	[DataMember]
    public string FetchXml { get; set; }

	[DataMember]
    public bool IsCustomizable { get; set; }

	[DataMember]
    public bool IsQuickFindQuery { get; set; }

	[DataMember]
    public string ColumnSetXml { get; set; }

	[DataMember]
    public string LayoutXml { get; set; }

	[DataMember]
    public Nullable<System.Guid> CreatedBy { get; set; }

	[DataMember]
    public Nullable<System.DateTime> CreatedOn { get; set; }

	[DataMember]
    public Nullable<System.Guid> ModifiedBy { get; set; }

	[DataMember]
    public Nullable<System.DateTime> ModifiedOn { get; set; }

	[DataMember]
    public byte[] VersionNumber { get; set; }

	[DataMember]
    public bool IsPrivate { get; set; }

	[DataMember]
    public string AdvancedGroupBy { get; set; }

	[DataMember]
    public string ConditionalFormatting { get; set; }

	[DataMember]
    public bool CanBeDeleted { get; set; }

	[DataMember]
    public Nullable<int> StatusCode { get; set; }

	[DataMember]
    public Nullable<System.Guid> QueryParentId { get; set; }

}

}
