
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Katrin.Services.Metadata
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
public partial class Subscription
{

	[DataMember]
    public System.Guid SubscriptionId { get; set; }

	[DataMember]
    public Nullable<System.Guid> UserId { get; set; }

	[DataMember]
    public Nullable<System.Guid> NotificationProfileId { get; set; }



	[DataMember]
    public virtual NotificationProfile NotificationProfile { get; set; }

}

}
