//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katrin.Win.MainModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Katrin.Win.MainModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual input can not zero.
        /// </summary>
        internal static string ActualInputIsZero {
            get {
                return ResourceManager.GetString("ActualInputIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Iteration.
        /// </summary>
        internal static string AddIteration {
            get {
                return ResourceManager.GetString("AddIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Module.
        /// </summary>
        internal static string AddModule {
            get {
                return ResourceManager.GetString("AddModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Time.
        /// </summary>
        internal static string AddTimeTracking {
            get {
                return ResourceManager.GetString("AddTimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Version.
        /// </summary>
        internal static string AddVersion {
            get {
                return ResourceManager.GetString("AddVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        internal static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Date.
        /// </summary>
        internal static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unregister site that was registered in parent: {0}.
        /// </summary>
        internal static string CannotUnregisterSiteRegisteredWithParent {
            get {
                return ResourceManager.GetString("CannotUnregisterSiteRegisteredWithParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katrin.
        /// </summary>
        internal static string Katrin {
            get {
                return ResourceManager.GetString("Katrin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate Exactly Rate.
        /// </summary>
        internal static string colEvaluateExactlyRate {
            get {
                return ResourceManager.GetString("colEvaluateExactlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Effort Rate.
        /// </summary>
        internal static string colInputEffortRate {
            get {
                return ResourceManager.GetString("colInputEffortRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum ActualInput.
        /// </summary>
        internal static string colSumActualInput {
            get {
                return ResourceManager.GetString("colSumActualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum ActualWorkHours.
        /// </summary>
        internal static string colSumActualWorkHours {
            get {
                return ResourceManager.GetString("colSumActualWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Effort.
        /// </summary>
        internal static string colSumEffort {
            get {
                return ResourceManager.GetString("colSumEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Overtime.
        /// </summary>
        internal static string colSumOvertime {
            get {
                return ResourceManager.GetString("colSumOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum QuoteWorkHours.
        /// </summary>
        internal static string colSumQuoteWorkHours {
            get {
                return ResourceManager.GetString("colSumQuoteWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum RemainderTime.
        /// </summary>
        internal static string colSumRemainderTime {
            get {
                return ResourceManager.GetString("colSumRemainderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        internal static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password doesn&apos;t match the password field..
        /// </summary>
        internal static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Date.
        /// </summary>
        internal static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Rang.
        /// </summary>
        internal static string DateRang {
            get {
                return ResourceManager.GetString("DateRang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta name=&quot;Generator&quot; content=&quot;Microsoft Word 12 (filtered medium)&quot;&gt;
        ///    &lt;title&gt;DailyReport&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        h1
        ///        {
        ///            margin: 0cm;
        ///            text-align: justify;
        ///            font-family: &quot;Calibri&quot; , &quot;sans-serif&quot;;
        ///            font-weight: normal;
        ///            margin-top: 1cm;
        ///            ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayReportTemplate {
            get {
                return ResourceManager.GetString("DayReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead.
        /// </summary>
        internal static string DeadLead {
            get {
                return ResourceManager.GetString("DeadLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to dead the {0}?.
        /// </summary>
        internal static string DeadRecord {
            get {
                return ResourceManager.GetString("DeadRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Note.
        /// </summary>
        internal static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this note?.
        /// </summary>
        internal static string DeleteNoteTip {
            get {
                return ResourceManager.GetString("DeleteNoteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Project Iteration?.
        /// </summary>
        internal static string DeleteProjectIterationTip {
            get {
                return ResourceManager.GetString("DeleteProjectIterationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this project module ?.
        /// </summary>
        internal static string DeleteProjectModuleTip {
            get {
                return ResourceManager.GetString("DeleteProjectModuleTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Project Task?.
        /// </summary>
        internal static string DeleteProjectTaskTip {
            get {
                return ResourceManager.GetString("DeleteProjectTaskTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Project Version?.
        /// </summary>
        internal static string DeleteProjectVersionTip {
            get {
                return ResourceManager.GetString("DeleteProjectVersionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected 1 {0} for deletion.
        ///
        ///The system will delete this record. This action cannot be undone. To continue, click OK..
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Time.
        /// </summary>
        internal static string DeleteTimeTracking {
            get {
                return ResourceManager.GetString("DeleteTimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this timeTracking?.
        /// </summary>
        internal static string DeleteTimingTip {
            get {
                return ResourceManager.GetString("DeleteTimingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete this {0} when it is used!.
        /// </summary>
        internal static string DisableDeleteRecord {
            get {
                return ResourceManager.GetString("DisableDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A UI extension site with this name already exists: {0}.
        /// </summary>
        internal static string DuplicateUIExtensionSite {
            get {
                return ResourceManager.GetString("DuplicateUIExtensionSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Effort.
        /// </summary>
        internal static string EditEffort {
            get {
                return ResourceManager.GetString("EditEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note.
        /// </summary>
        internal static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task Effort.
        /// </summary>
        internal static string EditTaskEffort {
            get {
                return ResourceManager.GetString("EditTaskEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Time.
        /// </summary>
        internal static string EditTimeTracking {
            get {
                return ResourceManager.GetString("EditTimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effort.
        /// </summary>
        internal static string Effort {
            get {
                return ResourceManager.GetString("Effort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Details - {1}.
        /// </summary>
        internal static string EntityDetailsCaptionFormat {
            get {
                return ResourceManager.GetString("EntityDetailsCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} List.
        /// </summary>
        internal static string EntityListCaptionFormat {
            get {
                return ResourceManager.GetString("EntityListCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High status should not drag To low status..
        /// </summary>
        internal static string ErrorDirection {
            get {
                return ResourceManager.GetString("ErrorDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Report.
        /// </summary>
        internal static string GenerateDayReport {
            get {
                return ResourceManager.GetString("GenerateDayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        internal static string GenerateWeekReport {
            get {
                return ResourceManager.GetString("GenerateWeekReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal.
        /// </summary>
        internal static string IdealRemainTime {
            get {
                return ResourceManager.GetString("IdealRemainTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline should be greater than Start Date..
        /// </summary>
        internal static string IterationDateCompareMessage {
            get {
                return ResourceManager.GetString("IterationDateCompareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the duration of iterations should not overlap..
        /// </summary>
        internal static string IterationDateErrorMessage {
            get {
                return ResourceManager.GetString("IterationDateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration Name.
        /// </summary>
        internal static string IterationName {
            get {
                return ResourceManager.GetString("IterationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quarter.
        /// </summary>
        internal static string LastQuarter {
            get {
                return ResourceManager.GetString("LastQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        internal static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        internal static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        internal static string Lead {
            get {
                return ResourceManager.GetString("Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string LeadConvert {
            get {
                return ResourceManager.GetString("LeadConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} List.
        /// </summary>
        internal static string ListScreenTitle {
            get {
                return ResourceManager.GetString("ListScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        internal static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewCommand {
            get {
                return ResourceManager.GetString("NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        internal static string NewEntity {
            get {
                return ResourceManager.GetString("NewEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you do not have  tasks today..
        /// </summary>
        internal static string NoNewTaskMessage {
            get {
                return ResourceManager.GetString("NoNewTaskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any task..
        /// </summary>
        internal static string NoTaskTip {
            get {
                return ResourceManager.GetString("NoTaskTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        internal static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity.
        /// </summary>
        internal static string Opportunity {
            get {
                return ResourceManager.GetString("Opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Report.
        /// </summary>
        internal static string OpportunityReport {
            get {
                return ResourceManager.GetString("OpportunityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total effort should not greater than total Actual Work Hours.
        /// </summary>
        internal static string OverEffortMessage {
            get {
                return ResourceManager.GetString("OverEffortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_add {
            get {
                object obj = ResourceManager.GetObject("overlay_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_delete {
            get {
                object obj = ResourceManager.GetObject("overlay_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_edit {
            get {
                object obj = ResourceManager.GetObject("overlay_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_search {
            get {
                object obj = ResourceManager.GetObject("overlay_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_view {
            get {
                object obj = ResourceManager.GetObject("overlay_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Time can not be bigger than effort.
        /// </summary>
        internal static string OverTimeTip {
            get {
                return ResourceManager.GetString("OverTimeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman  .
        /// </summary>
        internal static string OwnerPerson {
            get {
                return ResourceManager.GetString("OwnerPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password length should not be less than 6.
        /// </summary>
        internal static string PasswordLengthValidation {
            get {
                return ResourceManager.GetString("PasswordLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string PopupContract {
            get {
                return ResourceManager.GetString("PopupContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string PopupInvoice {
            get {
                return ResourceManager.GetString("PopupInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string PopupQuote {
            get {
                return ResourceManager.GetString("PopupQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability:.
        /// </summary>
        internal static string ProbabilityCode {
            get {
                return ResourceManager.GetString("ProbabilityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Iteration.
        /// </summary>
        internal static string ProjectIteration {
            get {
                return ResourceManager.GetString("ProjectIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management.
        /// </summary>
        internal static string ProjectManagement {
            get {
                return ResourceManager.GetString("ProjectManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        internal static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Member:.
        /// </summary>
        internal static string ProjectMember {
            get {
                return ResourceManager.GetString("ProjectMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Module.
        /// </summary>
        internal static string ProjectModule {
            get {
                return ResourceManager.GetString("ProjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name     .
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Report.
        /// </summary>
        internal static string ProjectReport {
            get {
                return ResourceManager.GetString("ProjectReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Task.
        /// </summary>
        internal static string ProjectTask {
            get {
                return ResourceManager.GetString("ProjectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Task Effort.
        /// </summary>
        internal static string ProjectTaskEffort {
            get {
                return ResourceManager.GetString("ProjectTaskEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type:.
        /// </summary>
        internal static string ProjectTypeCode {
            get {
                return ResourceManager.GetString("ProjectTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectVersion.
        /// </summary>
        internal static string ProjectVersion {
            get {
                return ResourceManager.GetString("ProjectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Report.
        /// </summary>
        internal static string ProjectWeekReport {
            get {
                return ResourceManager.GetString("ProjectWeekReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Is not nullable.
        /// </summary>
        internal static string ReasonNullTip {
            get {
                return ResourceManager.GetString("ReasonNullTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Recommended has blank value,do you wish to continue?.
        /// </summary>
        internal static string RecommendWarning {
            get {
                return ResourceManager.GetString("RecommendWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Management.
        /// </summary>
        internal static string RecordManagement {
            get {
                return ResourceManager.GetString("RecordManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Person.
        /// </summary>
        internal static string RecordPerson {
            get {
                return ResourceManager.GetString("RecordPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related.
        /// </summary>
        internal static string Related {
            get {
                return ResourceManager.GetString("Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_account {
            get {
                object obj = ResourceManager.GetObject("ri_account", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_admin {
            get {
                object obj = ResourceManager.GetObject("ri_admin", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_audit {
            get {
                object obj = ResourceManager.GetObject("ri_audit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_Katrin {
            get {
                object obj = ResourceManager.GetObject("ri_Katrin", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_contact {
            get {
                object obj = ResourceManager.GetObject("ri_contact", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_contract {
            get {
                object obj = ResourceManager.GetObject("ri_contract", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_Contract2 {
            get {
                object obj = ResourceManager.GetObject("ri_Contract2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_edit {
            get {
                object obj = ResourceManager.GetObject("ri_edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_error {
            get {
                object obj = ResourceManager.GetObject("ri_error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_exit {
            get {
                object obj = ResourceManager.GetObject("ri_exit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_format {
            get {
                object obj = ResourceManager.GetObject("ri_format", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_history {
            get {
                object obj = ResourceManager.GetObject("ri_history", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_invoice {
            get {
                object obj = ResourceManager.GetObject("ri_invoice", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_lead {
            get {
                object obj = ResourceManager.GetObject("ri_lead", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ri_login {
            get {
                object obj = ResourceManager.GetObject("ri_login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_note {
            get {
                object obj = ResourceManager.GetObject("ri_note", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_opportunity {
            get {
                object obj = ResourceManager.GetObject("ri_opportunity", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ri_overlay_exit {
            get {
                object obj = ResourceManager.GetObject("ri_overlay_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ri_overlay_ok {
            get {
                object obj = ResourceManager.GetObject("ri_overlay_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_product {
            get {
                object obj = ResourceManager.GetObject("ri_product", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_project {
            get {
                object obj = ResourceManager.GetObject("ri_project", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_projectmanagement {
            get {
                object obj = ResourceManager.GetObject("ri_projectmanagement", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_projecttask {
            get {
                object obj = ResourceManager.GetObject("ri_projecttask", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_qualify {
            get {
                object obj = ResourceManager.GetObject("ri_qualify", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_quote {
            get {
                object obj = ResourceManager.GetObject("ri_quote", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_refresh {
            get {
                object obj = ResourceManager.GetObject("ri_refresh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_role {
            get {
                object obj = ResourceManager.GetObject("ri_role", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_sales {
            get {
                object obj = ResourceManager.GetObject("ri_sales", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_save {
            get {
                object obj = ResourceManager.GetObject("ri_save", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_systemsetting {
            get {
                object obj = ResourceManager.GetObject("ri_systemsetting", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_timetracking {
            get {
                object obj = ResourceManager.GetObject("ri_timetracking", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_user {
            get {
                object obj = ResourceManager.GetObject("ri_user", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_userinfo {
            get {
                object obj = ResourceManager.GetObject("ri_userinfo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t select this item,it hava this operation above..
        /// </summary>
        internal static string SaleStageChangeTip {
            get {
                return ResourceManager.GetString("SaleStageChangeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save&amp;&amp;Close.
        /// </summary>
        internal static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceManagement.
        /// </summary>
        internal static string ServiceManagement {
            get {
                return ResourceManager.GetString("ServiceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Time Tracking.
        /// </summary>
        internal static string ShowTimeTracking {
            get {
                return ResourceManager.GetString("ShowTimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skins.
        /// </summary>
        internal static string Skins {
            get {
                return ResourceManager.GetString("Skins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status       .
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Input Rate.
        /// </summary>
        internal static string SumActualInputRate {
            get {
                return ResourceManager.GetString("SumActualInputRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effort Rate.
        /// </summary>
        internal static string SumEffortRate {
            get {
                return ResourceManager.GetString("SumEffortRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting.
        /// </summary>
        internal static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology:.
        /// </summary>
        internal static string TechnologyCode {
            get {
                return ResourceManager.GetString("TechnologyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical .
        /// </summary>
        internal static string TechnologyPerson {
            get {
                return ResourceManager.GetString("TechnologyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Quarter.
        /// </summary>
        internal static string ThisQuarter {
            get {
                return ResourceManager.GetString("ThisQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        internal static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Tracking.
        /// </summary>
        internal static string TimeTracking {
            get {
                return ResourceManager.GetString("TimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeTrackings.
        /// </summary>
        internal static string TimeTrackings {
            get {
                return ResourceManager.GetString("TimeTrackings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo.
        /// </summary>
        internal static string ToDoRemainTime {
            get {
                return ResourceManager.GetString("ToDoRemainTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        internal static string Unassigned {
            get {
                return ResourceManager.GetString("Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name and password are invalid..
        /// </summary>
        internal static string UserNameAndPasswordInvalid {
            get {
                return ResourceManager.GetString("UserNameAndPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date is invalidation.
        /// </summary>
        internal static string ValidateDate {
            get {
                return ResourceManager.GetString("ValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty.
        /// </summary>
        internal static string ValidateNotBlankMessage {
            get {
                return ResourceManager.GetString("ValidateNotBlankMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewPageCaption {
            get {
                return ResourceManager.GetString("ViewPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;NewWeekReporter&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body.Sumbody{ lang:ZH-CN ;link:blue;vlink:purple;text-justify-trim:punctuation;}
        ///        div.Section1{page:Section1;}
        ///        .MsoNormal{margin:0cm;margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;font-size:10.5pt;font-family:&quot;Calibri&quot;,&quot;sans-seri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeekReportTemplate {
            get {
                return ResourceManager.GetString("WeekReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        internal static string Won {
            get {
                return ResourceManager.GetString("Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Unit.
        /// </summary>
        internal static string WorkUnit {
            get {
                return ResourceManager.GetString("WorkUnit", resourceCulture);
            }
        }
    }
}
