//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katrin.Win.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Katrin.Win.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance Tasks.
        /// </summary>
        internal static string AcceptanceTasks {
            get {
                return ResourceManager.GetString("AcceptanceTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Quotes.
        /// </summary>
        internal static string AcceptedQuotes {
            get {
                return ResourceManager.GetString("AcceptedQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Filter.
        /// </summary>
        internal static string AddFilter {
            get {
                return ResourceManager.GetString("AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Iteration.
        /// </summary>
        internal static string AddIteration {
            get {
                return ResourceManager.GetString("AddIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Time.
        /// </summary>
        internal static string AddTimeTracking {
            get {
                return ResourceManager.GetString("AddTimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Version.
        /// </summary>
        internal static string AddVersion {
            get {
                return ResourceManager.GetString("AddVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Contracts.
        /// </summary>
        internal static string AllMyContracts {
            get {
                return ResourceManager.GetString("AllMyContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Invoices.
        /// </summary>
        internal static string AllMyInvoices {
            get {
                return ResourceManager.GetString("AllMyInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Leads.
        /// </summary>
        internal static string AllMyLeads {
            get {
                return ResourceManager.GetString("AllMyLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Opportunities.
        /// </summary>
        internal static string AllMyOpportunities {
            get {
                return ResourceManager.GetString("AllMyOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Opportunities In This Month.
        /// </summary>
        internal static string AllMyOpportunitiesInThisMonth {
            get {
                return ResourceManager.GetString("AllMyOpportunitiesInThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Projects.
        /// </summary>
        internal static string AllMyProjects {
            get {
                return ResourceManager.GetString("AllMyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Quotes.
        /// </summary>
        internal static string AllMyQuotes {
            get {
                return ResourceManager.GetString("AllMyQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Tasks.
        /// </summary>
        internal static string AllMyTasks {
            get {
                return ResourceManager.GetString("AllMyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Week Reports.
        /// </summary>
        internal static string AllMyWeekReports {
            get {
                return ResourceManager.GetString("AllMyWeekReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        internal static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Debt Invoices.
        /// </summary>
        internal static string BadDebtInvoices {
            get {
                return ResourceManager.GetString("BadDebtInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unregister site that was registered in parent: {0}.
        /// </summary>
        internal static string CannotUnregisterSiteRegisteredWithParent {
            get {
                return ResourceManager.GetString("CannotUnregisterSiteRegisteredWithParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Setting.
        /// </summary>
        internal static string ClearSetting {
            get {
                return ResourceManager.GetString("ClearSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system will clear your local settings. This action cannot be undone. To continue, click OK.
        /// </summary>
        internal static string ClearSettingConfirm {
            get {
                return ResourceManager.GetString("ClearSettingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Contracts.
        /// </summary>
        internal static string ClosedContracts {
            get {
                return ResourceManager.GetString("ClosedContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katrin.
        /// </summary>
        internal static string Katrin {
            get {
                return ResourceManager.GetString("Katrin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate Exactly Rate.
        /// </summary>
        internal static string colEvaluateExactlyRate {
            get {
                return ResourceManager.GetString("colEvaluateExactlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Effort Rate.
        /// </summary>
        internal static string colInputEffortRate {
            get {
                return ResourceManager.GetString("colInputEffortRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum ActualInput.
        /// </summary>
        internal static string colSumActualInput {
            get {
                return ResourceManager.GetString("colSumActualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum ActualWorkHours.
        /// </summary>
        internal static string colSumActualWorkHours {
            get {
                return ResourceManager.GetString("colSumActualWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Effort.
        /// </summary>
        internal static string colSumEffort {
            get {
                return ResourceManager.GetString("colSumEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Overtime.
        /// </summary>
        internal static string colSumOvertime {
            get {
                return ResourceManager.GetString("colSumOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum QuoteWorkHours.
        /// </summary>
        internal static string colSumQuoteWorkHours {
            get {
                return ResourceManager.GetString("colSumQuoteWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum RemainderTime.
        /// </summary>
        internal static string colSumRemainderTime {
            get {
                return ResourceManager.GetString("colSumRemainderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string ColumnCaptionFormat {
            get {
                return ResourceManager.GetString("ColumnCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Projects.
        /// </summary>
        internal static string CompletedProjects {
            get {
                return ResourceManager.GetString("CompletedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Tasks.
        /// </summary>
        internal static string CompletedTasks {
            get {
                return ResourceManager.GetString("CompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        internal static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password doesn&apos;t match the password field..
        /// </summary>
        internal static string ConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted Leads.
        /// </summary>
        internal static string ConvertedLeads {
            get {
                return ResourceManager.GetString("ConvertedLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string ConvertTitle {
            get {
                return ResourceManager.GetString("ConvertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy&amp;&amp;New.
        /// </summary>
        internal static string CopyAndNew {
            get {
                return ResourceManager.GetString("CopyAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covert to {0}.
        /// </summary>
        internal static string Covert {
            get {
                return ResourceManager.GetString("Covert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead.
        /// </summary>
        internal static string DeadLead {
            get {
                return ResourceManager.GetString("DeadLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Leads.
        /// </summary>
        internal static string DeadLeads {
            get {
                return ResourceManager.GetString("DeadLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to dead the {0}?.
        /// </summary>
        internal static string DeadRecord {
            get {
                return ResourceManager.GetString("DeadRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Filter.
        /// </summary>
        internal static string DeleteFilter {
            get {
                return ResourceManager.GetString("DeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this filter?.
        /// </summary>
        internal static string DeleteFilterTip {
            get {
                return ResourceManager.GetString("DeleteFilterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this item?.
        /// </summary>
        internal static string DeleteListItemWarning {
            get {
                return ResourceManager.GetString("DeleteListItemWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Note.
        /// </summary>
        internal static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Notification.
        /// </summary>
        internal static string DeleteNotification {
            get {
                return ResourceManager.GetString("DeleteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Project Iteration?.
        /// </summary>
        internal static string DeleteProjectIterationTip {
            get {
                return ResourceManager.GetString("DeleteProjectIterationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Project Task?.
        /// </summary>
        internal static string DeleteProjectTaskTip {
            get {
                return ResourceManager.GetString("DeleteProjectTaskTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Project Version?.
        /// </summary>
        internal static string DeleteProjectVersionTip {
            get {
                return ResourceManager.GetString("DeleteProjectVersionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected 1 {0} for deletion.
        ///
        ///The system will delete this record. This action cannot be undone. To continue, click OK..
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Time.
        /// </summary>
        internal static string DeleteTimeTracking {
            get {
                return ResourceManager.GetString("DeleteTimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        internal static string Diagram {
            get {
                return ResourceManager.GetString("Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete this {0} when it is used!.
        /// </summary>
        internal static string DisableDeleteRecord {
            get {
                return ResourceManager.GetString("DisableDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A UI extension site with this name already exists: {0}.
        /// </summary>
        internal static string DuplicateUIExtensionSite {
            get {
                return ResourceManager.GetString("DuplicateUIExtensionSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Effort.
        /// </summary>
        internal static string EditEffort {
            get {
                return ResourceManager.GetString("EditEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filter.
        /// </summary>
        internal static string EditFilter {
            get {
                return ResourceManager.GetString("EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Note.
        /// </summary>
        internal static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task Effort.
        /// </summary>
        internal static string EditTaskEffort {
            get {
                return ResourceManager.GetString("EditTaskEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Time.
        /// </summary>
        internal static string EditTimeTracking {
            get {
                return ResourceManager.GetString("EditTimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effort.
        /// </summary>
        internal static string Effort {
            get {
                return ResourceManager.GetString("Effort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Details.
        /// </summary>
        internal static string EntityDetailsCaptionFormat {
            get {
                return ResourceManager.GetString("EntityDetailsCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} List.
        /// </summary>
        internal static string EntityListCaptionFormat {
            get {
                return ResourceManager.GetString("EntityListCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Contracts.
        /// </summary>
        internal static string FailedContracts {
            get {
                return ResourceManager.GetString("FailedContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Operate.
        /// </summary>
        internal static string FastOperate {
            get {
                return ResourceManager.GetString("FastOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Contracts.
        /// </summary>
        internal static string FinishedContracts {
            get {
                return ResourceManager.GetString("FinishedContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Report.
        /// </summary>
        internal static string GenerateDayReport {
            get {
                return ResourceManager.GetString("GenerateDayReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        internal static string GenerateWeekReport {
            get {
                return ResourceManager.GetString("GenerateWeekReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Arrear Invoices.
        /// </summary>
        internal static string InArrearInvoices {
            get {
                return ResourceManager.GetString("InArrearInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress Projects.
        /// </summary>
        internal static string InProgressProjects {
            get {
                return ResourceManager.GetString("InProgressProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress Tasks.
        /// </summary>
        internal static string InProgressTasks {
            get {
                return ResourceManager.GetString("InProgressTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        internal static string Lead {
            get {
                return ResourceManager.GetString("Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string LeadConvert {
            get {
                return ResourceManager.GetString("LeadConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Opened Last Week.
        /// </summary>
        internal static string LeadOpenedLastWeek {
            get {
                return ResourceManager.GetString("LeadOpenedLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Opened This Week.
        /// </summary>
        internal static string LeadOpenedThisWeek {
            get {
                return ResourceManager.GetString("LeadOpenedThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} List.
        /// </summary>
        internal static string ListScreenTitle {
            get {
                return ResourceManager.GetString("ListScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Opportunities.
        /// </summary>
        internal static string LostOpportunities {
            get {
                return ResourceManager.GetString("LostOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Quotes.
        /// </summary>
        internal static string LostQuotes {
            get {
                return ResourceManager.GetString("LostQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Filter.
        /// </summary>
        internal static string ManageFilter {
            get {
                return ResourceManager.GetString("ManageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Open Contracts.
        /// </summary>
        internal static string MyOpenContracts {
            get {
                return ResourceManager.GetString("MyOpenContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Open Leads.
        /// </summary>
        internal static string MyOpenLeads {
            get {
                return ResourceManager.GetString("MyOpenLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Open Opportunities.
        /// </summary>
        internal static string MyOpenOpportunities {
            get {
                return ResourceManager.GetString("MyOpenOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Open Quotes.
        /// </summary>
        internal static string MyOpenQuotes {
            get {
                return ResourceManager.GetString("MyOpenQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewCommand {
            get {
                return ResourceManager.GetString("NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        internal static string NewEntity {
            get {
                return ResourceManager.GetString("NewEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project Task Effort.
        /// </summary>
        internal static string NewProjectTaskEffort {
            get {
                return ResourceManager.GetString("NewProjectTaskEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Related Data!.
        /// </summary>
        internal static string NoRelatedData {
            get {
                return ResourceManager.GetString("NoRelatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notificationb {
            get {
                object obj = ResourceManager.GetObject("notificationb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started Projects.
        /// </summary>
        internal static string NotStartedProjects {
            get {
                return ResourceManager.GetString("NotStartedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started Tasks.
        /// </summary>
        internal static string NotStartedTasks {
            get {
                return ResourceManager.GetString("NotStartedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Contracts.
        /// </summary>
        internal static string OpenContracts {
            get {
                return ResourceManager.GetString("OpenContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Leads.
        /// </summary>
        internal static string OpenLeads {
            get {
                return ResourceManager.GetString("OpenLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open My Opportunities Before This Month.
        /// </summary>
        internal static string OpenMyOpportunitiesBeforeThisMonth {
            get {
                return ResourceManager.GetString("OpenMyOpportunitiesBeforeThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Opportunities.
        /// </summary>
        internal static string OpenOpportunities {
            get {
                return ResourceManager.GetString("OpenOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Quotes.
        /// </summary>
        internal static string OpenQuotes {
            get {
                return ResourceManager.GetString("OpenQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities Created in This Month.
        /// </summary>
        internal static string OpportunitiesCreatedinThisMonth {
            get {
                return ResourceManager.GetString("OpportunitiesCreatedinThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity.
        /// </summary>
        internal static string Opportunity {
            get {
                return ResourceManager.GetString("Opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Opened Last Week.
        /// </summary>
        internal static string OpportunityOpenedLastWeek {
            get {
                return ResourceManager.GetString("OpportunityOpenedLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Opened This Week.
        /// </summary>
        internal static string OpportunityOpenedThisWeek {
            get {
                return ResourceManager.GetString("OpportunityOpenedThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_add {
            get {
                object obj = ResourceManager.GetObject("overlay_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_convert {
            get {
                object obj = ResourceManager.GetObject("overlay_convert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_delete {
            get {
                object obj = ResourceManager.GetObject("overlay_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_edit {
            get {
                object obj = ResourceManager.GetObject("overlay_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_search {
            get {
                object obj = ResourceManager.GetObject("overlay_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overlay_view {
            get {
                object obj = ResourceManager.GetObject("overlay_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Invoices.
        /// </summary>
        internal static string PaidInvoices {
            get {
                return ResourceManager.GetString("PaidInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password length should not be less than 6.
        /// </summary>
        internal static string PasswordLengthValidation {
            get {
                return ResourceManager.GetString("PasswordLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Invoices.
        /// </summary>
        internal static string PlannedInvoices {
            get {
                return ResourceManager.GetString("PlannedInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string PopupContract {
            get {
                return ResourceManager.GetString("PopupContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string PopupInvoice {
            get {
                return ResourceManager.GetString("PopupInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string PopupQuote {
            get {
                return ResourceManager.GetString("PopupQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Iteration.
        /// </summary>
        internal static string ProjectIteration {
            get {
                return ResourceManager.GetString("ProjectIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Task.
        /// </summary>
        internal static string ProjectTask {
            get {
                return ResourceManager.GetString("ProjectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Task Effort.
        /// </summary>
        internal static string ProjectTaskEffort {
            get {
                return ResourceManager.GetString("ProjectTaskEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectVersion.
        /// </summary>
        internal static string ProjectVersion {
            get {
                return ResourceManager.GetString("ProjectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Report.
        /// </summary>
        internal static string ProjectWeekReport {
            get {
                return ResourceManager.GetString("ProjectWeekReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Management.
        /// </summary>
        internal static string RecordManagement {
            get {
                return ResourceManager.GetString("RecordManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related.
        /// </summary>
        internal static string Related {
            get {
                return ResourceManager.GetString("Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Tool.
        /// </summary>
        internal static string ReportTool {
            get {
                return ResourceManager.GetString("ReportTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_account {
            get {
                object obj = ResourceManager.GetObject("ri_account", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_addnote {
            get {
                object obj = ResourceManager.GetObject("ri_addnote", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_addtimetracking {
            get {
                object obj = ResourceManager.GetObject("ri_addtimetracking", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_admin {
            get {
                object obj = ResourceManager.GetObject("ri_admin", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_audit {
            get {
                object obj = ResourceManager.GetObject("ri_audit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ri_clear {
            get {
                object obj = ResourceManager.GetObject("ri_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_Katrin {
            get {
                object obj = ResourceManager.GetObject("ri_Katrin", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_contact {
            get {
                object obj = ResourceManager.GetObject("ri_contact", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_contract {
            get {
                object obj = ResourceManager.GetObject("ri_contract", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_Contract2 {
            get {
                object obj = ResourceManager.GetObject("ri_Contract2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_edit {
            get {
                object obj = ResourceManager.GetObject("ri_edit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_entity {
            get {
                object obj = ResourceManager.GetObject("ri_entity", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_error {
            get {
                object obj = ResourceManager.GetObject("ri_error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_exit {
            get {
                object obj = ResourceManager.GetObject("ri_exit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_format {
            get {
                object obj = ResourceManager.GetObject("ri_format", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_history {
            get {
                object obj = ResourceManager.GetObject("ri_history", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_invoice {
            get {
                object obj = ResourceManager.GetObject("ri_invoice", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_lead {
            get {
                object obj = ResourceManager.GetObject("ri_lead", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ri_login {
            get {
                object obj = ResourceManager.GetObject("ri_login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_note {
            get {
                object obj = ResourceManager.GetObject("ri_note", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_opportunity {
            get {
                object obj = ResourceManager.GetObject("ri_opportunity", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ri_overlay_exit {
            get {
                object obj = ResourceManager.GetObject("ri_overlay_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ri_overlay_ok {
            get {
                object obj = ResourceManager.GetObject("ri_overlay_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_product {
            get {
                object obj = ResourceManager.GetObject("ri_product", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_project {
            get {
                object obj = ResourceManager.GetObject("ri_project", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_projecttask {
            get {
                object obj = ResourceManager.GetObject("ri_projecttask", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_qualify {
            get {
                object obj = ResourceManager.GetObject("ri_qualify", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_quote {
            get {
                object obj = ResourceManager.GetObject("ri_quote", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_refresh {
            get {
                object obj = ResourceManager.GetObject("ri_refresh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_role {
            get {
                object obj = ResourceManager.GetObject("ri_role", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_sales {
            get {
                object obj = ResourceManager.GetObject("ri_sales", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_save {
            get {
                object obj = ResourceManager.GetObject("ri_save", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_service {
            get {
                object obj = ResourceManager.GetObject("ri_service", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_setopportunityfail {
            get {
                object obj = ResourceManager.GetObject("ri_setopportunityfail", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_setopportunityresurrection {
            get {
                object obj = ResourceManager.GetObject("ri_setopportunityresurrection", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_setopportunitysuccess {
            get {
                object obj = ResourceManager.GetObject("ri_setopportunitysuccess", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_systemsetting {
            get {
                object obj = ResourceManager.GetObject("ri_systemsetting", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_timetracking {
            get {
                object obj = ResourceManager.GetObject("ri_timetracking", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_user {
            get {
                object obj = ResourceManager.GetObject("ri_user", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ri_userinfo {
            get {
                object obj = ResourceManager.GetObject("ri_userinfo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save&amp;&amp;Close.
        /// </summary>
        internal static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        internal static string SendSysMessage {
            get {
                return ResourceManager.GetString("SendSysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sendsysmsg {
            get {
                object obj = ResourceManager.GetObject("sendsysmsg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Invoices.
        /// </summary>
        internal static string SentInvoices {
            get {
                return ResourceManager.GetString("SentInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceManagement.
        /// </summary>
        internal static string ServiceManagement {
            get {
                return ResourceManager.GetString("ServiceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Time Tracking.
        /// </summary>
        internal static string ShowTimeTracking {
            get {
                return ResourceManager.GetString("ShowTimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skins.
        /// </summary>
        internal static string Skins {
            get {
                return ResourceManager.GetString("Skins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status      .
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting.
        /// </summary>
        internal static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tag {
            get {
                object obj = ResourceManager.GetObject("tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attendance In Last Month.
        /// </summary>
        internal static string TheAttendanceInLastMonth {
            get {
                return ResourceManager.GetString("TheAttendanceInLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attendance In This Month.
        /// </summary>
        internal static string TheAttendanceInThisMonth {
            get {
                return ResourceManager.GetString("TheAttendanceInThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attendance In This Year.
        /// </summary>
        internal static string TheAttendanceInThisYear {
            get {
                return ResourceManager.GetString("TheAttendanceInThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Recent Active Contacts.
        /// </summary>
        internal static string TheRecentActiveContacts {
            get {
                return ResourceManager.GetString("TheRecentActiveContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Recent Active Customers.
        /// </summary>
        internal static string TheRecentActiveCustomers {
            get {
                return ResourceManager.GetString("TheRecentActiveCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Tracking.
        /// </summary>
        internal static string TimeTracking {
            get {
                return ResourceManager.GetString("TimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeTrackings.
        /// </summary>
        internal static string TimeTrackings {
            get {
                return ResourceManager.GetString("TimeTrackings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap userinfo {
            get {
                object obj = ResourceManager.GetObject("userinfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name and password are invalid..
        /// </summary>
        internal static string UserNameAndPasswordInvalid {
            get {
                return ResourceManager.GetString("UserNameAndPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date is invalidation.
        /// </summary>
        internal static string ValidateDate {
            get {
                return ResourceManager.GetString("ValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty.
        /// </summary>
        internal static string ValidateNotBlankMessage {
            get {
                return ResourceManager.GetString("ValidateNotBlankMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewPageCaption {
            get {
                return ResourceManager.GetString("ViewPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Report.
        /// </summary>
        internal static string WeekReport {
            get {
                return ResourceManager.GetString("WeekReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won Opportunity.
        /// </summary>
        internal static string WonOpportunity {
            get {
                return ResourceManager.GetString("WonOpportunity", resourceCulture);
            }
        }
    }
}
