-- =============================================
-- Script Template
-- =============================================



CREATE PROCEDURE [dbo].[InsertLocalizedLabel] 
	@EntityName		 nvarchar(64),
	@AttributeName	 nvarchar(50),
	@LanguageId int,
	@LocalizedLabel nvarchar(MAX)
AS
BEGIN
	DECLARE @ObjectId uniqueidentifier
	
	PRINT @EntityName +'***' +@AttributeName
	
	SELECT	@ObjectId	= a.AttributeId
	FROm	[dbo].[Metadata_Attribute] a
			INNER JOIN [dbo].[Metadata_Entity] e
			ON	e.EntityId	= a.EntityId
	WHERE	e.Name = @EntityName AND a.Name = @AttributeName
		

	INSERT INTO [dbo].[Metadata_LocalizedLabel] ([LocalizedLabelId], [LanguageId], [ObjectId], [ObjectColumnName], [Label])  
	VALUES (NEWID(), @LanguageId, @ObjectId, N'DisplayName', @LocalizedLabel)
END

GO

BEGIN TRANSACTION

delete from Metadata_LocalizedLabel where LocalizedLabelId not in(
select distinct  a.LocalizedLabelId from Metadata_LocalizedLabel a  inner join Metadata_AttributePicklistValue b
on a.ObjectId = b.AttributePicklistValueId)--删除optionset之外的具体值

EXEC [dbo].[InsertLocalizedLabel] 'lead','FullName',2052,N'全名'
EXEC [dbo].[InsertLocalizedLabel] 'lead','FullName',1033,N'FullName'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Subject',2052,N'主题'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Subject',1033,N'Topic'
EXEC [dbo].[InsertLocalizedLabel] 'lead','TechnologyCode',2052,N'技术领域'
EXEC [dbo].[InsertLocalizedLabel] 'lead','TechnologyCode',1033,N'Technology'

EXEC [dbo].[InsertLocalizedLabel] 'lead','OwnerId',2052,N'拥有者'
EXEC [dbo].[InsertLocalizedLabel] 'lead','OwnerId',1033,N'Assign To'

EXEC [dbo].[InsertLocalizedLabel] 'lead','FirstName',2052,N'名'
EXEC [dbo].[InsertLocalizedLabel] 'lead','FirstName',1033,N'FirstName'
EXEC [dbo].[InsertLocalizedLabel] 'lead','MiddleName',2052,N''
EXEC [dbo].[InsertLocalizedLabel] 'lead','MiddleName',1033,N'MiddleName'
EXEC [dbo].[InsertLocalizedLabel] 'lead','LastName',2052,N'姓'
EXEC [dbo].[InsertLocalizedLabel] 'lead','LastName',1033,N'LastName'
EXEC [dbo].[InsertLocalizedLabel] 'lead','DepartmentId',2052,N'部门'
EXEC [dbo].[InsertLocalizedLabel] 'lead','DepartmentId',1033,N'Department Name'
EXEC [dbo].[InsertLocalizedLabel] 'lead','StatusCode',2052,N'状态'
EXEC [dbo].[InsertLocalizedLabel] 'lead','StatusCode',1033,N'Status'
EXEC [dbo].[InsertLocalizedLabel] 'lead','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'lead','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'lead','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'lead','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'lead','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'lead','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'lead','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'lead','CreatedById',1033,N'Created By'

EXEC [dbo].[InsertLocalizedLabel] 'lead','LeadSourceCode',2052,N'线索来源'
EXEC [dbo].[InsertLocalizedLabel] 'lead','LeadSourceCode',1033,N'Lead Source'
EXEC [dbo].[InsertLocalizedLabel] 'lead','CompanyName',2052,N'公司'
EXEC [dbo].[InsertLocalizedLabel] 'lead','CompanyName',1033,N'Company Name'
EXEC [dbo].[InsertLocalizedLabel] 'lead','PriorityCode',2052,N'优先级'
EXEC [dbo].[InsertLocalizedLabel] 'lead','PriorityCode',1033,N'Priority'
EXEC [dbo].[InsertLocalizedLabel] 'lead','NumberOfEmployees',2052,N'员工人数'
EXEC [dbo].[InsertLocalizedLabel] 'lead','NumberOfEmployees',1033,N'Number Of Employees'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Revenue',2052,N'年利润'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Revenue',1033,N'Revenue'
EXEC [dbo].[InsertLocalizedLabel] 'lead','OriginalMessage',2052,N'留言地址'
EXEC [dbo].[InsertLocalizedLabel] 'lead','OriginalMessage',1033,N'Original Message'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Description',2052,N'备注'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Description',1033,N'Description'
EXEC [dbo].[InsertLocalizedLabel] 'lead','MobilePhone',2052,N'移动电话'
EXEC [dbo].[InsertLocalizedLabel] 'lead','MobilePhone',1033,N'MobilePhone'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Telephone1',2052,N'公司电话'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Telephone1',1033,N'Bussiness Phone'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Telephone2',2052,N'家庭电话'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Telephone2',1033,N'Home Phone'
EXEC [dbo].[InsertLocalizedLabel] 'lead','EmailAddress',2052,N'邮箱地址'
EXEC [dbo].[InsertLocalizedLabel] 'lead','EmailAddress',1033,N'Email'
EXEC [dbo].[InsertLocalizedLabel] 'lead','CountryCode',2052,N'国家'
EXEC [dbo].[InsertLocalizedLabel] 'lead','CountryCode',1033,N'Country' 
EXEC [dbo].[InsertLocalizedLabel] 'lead','Country',2052,N'国家'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Country',1033,N'Country'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Address',2052,N'地址'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Address',1033,N'Address'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Fax',2052,N'传真'
EXEC [dbo].[InsertLocalizedLabel] 'lead','Fax',1033,N'Fax'
EXEC [dbo].[InsertLocalizedLabel] 'lead','WebSiteUrl',2052,N'网站'
EXEC [dbo].[InsertLocalizedLabel] 'lead','WebSiteUrl',1033,N'Web Site'
EXEC [dbo].[InsertLocalizedLabel] 'lead','City',2052,N'城市'
EXEC [dbo].[InsertLocalizedLabel] 'lead','City',1033,N'City'
EXEC [dbo].[InsertLocalizedLabel] 'lead','ZIP',2052,N'邮编'
EXEC [dbo].[InsertLocalizedLabel] 'lead','ZIP',1033,N'ZIP'

EXEC [dbo].[InsertLocalizedLabel] 'Quote','QuoteNumber',2052,N'报价编号'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','QuoteNumber',1033,N'Quote Number'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','Name',2052,N'项目名称'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','Name',1033,N'Name'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','TotalAmount',2052,N'报价金额'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','TotalAmount',1033,N'Total Amount'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','StageCode',2052,N'阶段'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','StageCode',1033,N'Stage'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','StatusCode',2052,N'状态'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','StatusCode',1033,N'Status'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','OwnerId',2052,N'所有者'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','OwnerId',1033,N'Owner'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','ExpiresOn',2052,N'终止日期'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','ExpiresOn',1033,N'Expires On'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','OpportunityId',2052,N'商业机遇'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','OpportunityId',1033,N'Opportunity'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','BillTo_AddressId',2052,N'账单地址'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','BillTo_AddressId',1033,N'Billing Address'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','BillTo_ContactName',2052,N'账单联系人'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','BillTo_ContactName',1033,N'Bill To Contact Name'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','PaymentTermsCode',2052,N'付款方式'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','PaymentTermsCode',1033,N'Payment Terms'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','ExchangeRate',2052,N'汇率'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','ExchangeRate',1033,N'Exchange Rate'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','Description',1033,N'Description'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','TotalTax',2052,N'总税收'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','TotalTax',1033,N'Total Tax'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','TotalDiscountAmount',2052,N'总折扣'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','TotalDiscountAmount',1033,N'Total Discount Amount'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','TotalLineItemAmount',2052,N'明细项目总额'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','TotalLineItemAmount',1033,N'Total Line Item Amount'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','TransactionCurrencyId',2052,N'货币'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','TransactionCurrencyId',1033,N'Currency'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','CustomerId',2052,N'客户'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','CustomerId',1033,N'Customer'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','QuoteId',2052,N'报价ID'
EXEC [dbo].[InsertLocalizedLabel] 'Quote','QuoteId',1033,N'Quote Id'
--EXEC [dbo].[InsertLocalizedLabel] 'Quote','StateOrProvince',2052,N'州或省'
--EXEC [dbo].[InsertLocalizedLabel] 'Quote','StateOrProvince',1033,N'State Or Province' 
--EXEC [dbo].[InsertLocalizedLabel] 'Quote','City',2052,N'城市'
--EXEC [dbo].[InsertLocalizedLabel] 'Quote','City',1033,N'City' 
--EXEC [dbo].[InsertLocalizedLabel] 'Quote','City',2052,N'国家'
--EXEC [dbo].[InsertLocalizedLabel] 'Quote','City',1033,N'Country'
--EXEC [dbo].[InsertLocalizedLabel] 'Quote','PostalCode',2052,N'邮政编码'
--EXEC [dbo].[InsertLocalizedLabel] 'Quote','PostalCode',1033,N'PostalCode'

EXEC [dbo].[InsertLocalizedLabel] 'Invoice','InvoiceNumber',2052,N'发票编号'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','InvoiceNumber',1033,N'Invoice Number'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','Name',2052,N'发票名'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','Name',1033,N'Name'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','BillingCustomerId',2052,N'客户'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','BillingCustomerId',1033,N'Customer'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','TotalAmount',2052,N'总金额'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','TotalAmount',1033,N'Total Amount'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','PaidAmount',2052,N'已付款项'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','PaidAmount',1033,N'Paid Amount'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','DateDelivered',2052,N'寄送日期'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','DateDelivered',1033,N'Date Delivered'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','ReceivedDate',2052,N'收款日期'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','ReceivedDate',1033,N'Received Date'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','OwnerId',2052,N'所有者'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','OwnerId',1033,N'Owner'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','StatusCode',2052,N'状态'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','StatusCode',1033,N'Status'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','TransactionCurrencyId',2052,N'货币'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','TransactionCurrencyId',1033,N'Currency'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','ExchangeRate',2052,N'汇率'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','ExchangeRate',1033,N'Exchange Rate'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'Invoice','Description',1033,N'Description'

EXEC [dbo].[InsertLocalizedLabel] 'Account','Name',2052,N'客户'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Name',1033,N'Account Name'
EXEC [dbo].[InsertLocalizedLabel] 'Account','PrimaryContactId',2052,N'最初联系人'
EXEC [dbo].[InsertLocalizedLabel] 'Account','PrimaryContactId',1033,N'Primary Contact'
EXEC [dbo].[InsertLocalizedLabel] 'Account','PrimaryContactId',2052,N'最初联系人'
EXEC [dbo].[InsertLocalizedLabel] 'Account','PrimaryContactId',1033,N'Primary Contact'
EXEC [dbo].[InsertLocalizedLabel] 'Account','OwnerId',2052,N'所有者'
EXEC [dbo].[InsertLocalizedLabel] 'Account','OwnerId',1033,N'Owner'
EXEC [dbo].[InsertLocalizedLabel] 'Account','StatusCode',2052,N'状态'
EXEC [dbo].[InsertLocalizedLabel] 'Account','StatusCode',1033,N'Status'
EXEC [dbo].[InsertLocalizedLabel] 'Account','EMailAddress1',2052,N'邮箱地址'
EXEC [dbo].[InsertLocalizedLabel] 'Account','EMailAddress1',1033,N'E-mail'
EXEC [dbo].[InsertLocalizedLabel] 'Account','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'Account','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'Account','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'Account','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'Account','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'Account','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'Account','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'Account','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'Account','WebSiteURL',2052,N'网站链接'
EXEC [dbo].[InsertLocalizedLabel] 'Account','WebSiteURL',1033,N'Web Site URL'
EXEC [dbo].[InsertLocalizedLabel] 'Account','ParentAccountId',2052,N'父帐户'
EXEC [dbo].[InsertLocalizedLabel] 'Account','ParentAccountId',1033,N'Parent Account'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Telephone1',2052,N'主要联系电话'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Telephone1',1033,N'Main Phone'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Telephone2',2052,N'其他联系电话'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Telephone2',1033,N'Other Phone'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Country',2052,N'国家'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Country',1033,N'Country'
EXEC [dbo].[InsertLocalizedLabel] 'Account','City',2052,N'城市'
EXEC [dbo].[InsertLocalizedLabel] 'Account','City',1033,N'City'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Description',1033,N'Description'
EXEC [dbo].[InsertLocalizedLabel] 'Account','IndustryCode',2052,N'行业'
EXEC [dbo].[InsertLocalizedLabel] 'Account','IndustryCode',1033,N'Industry'
EXEC [dbo].[InsertLocalizedLabel] 'Account','AccountRatingCode',2052,N'客户等级'
EXEC [dbo].[InsertLocalizedLabel] 'Account','AccountRatingCode',1033,N'Account Rating'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Revenue',2052,N'年利润'
EXEC [dbo].[InsertLocalizedLabel] 'Account','Revenue',1033,N'Revenue'
EXEC [dbo].[InsertLocalizedLabel] 'Account','OwnershipCode',2052,N'所有权'
EXEC [dbo].[InsertLocalizedLabel] 'Account','OwnershipCode',1033,N'Ownership'
EXEC [dbo].[InsertLocalizedLabel] 'Account','NumberOfEmployees',2052,N'员工人数'
EXEC [dbo].[InsertLocalizedLabel] 'Account','NumberOfEmployees',1033,N'Number Of Employees'
EXEC [dbo].[InsertLocalizedLabel] 'Account','TickerSymbol',2052,N'股票代号'
EXEC [dbo].[InsertLocalizedLabel] 'Account','TickerSymbol',1033,N'Ticker Symbol'
EXEC [dbo].[InsertLocalizedLabel] 'Account','SIC',2052,N'标准产业分类'
EXEC [dbo].[InsertLocalizedLabel] 'Account','SIC',1033,N'SIC'
EXEC [dbo].[InsertLocalizedLabel] 'Account','AccountCategoryCode',2052,N'客户类型'
EXEC [dbo].[InsertLocalizedLabel] 'Account','AccountCategoryCode',1033,N'Account Category'
EXEC [dbo].[InsertLocalizedLabel] 'Account','AccountClassificationCode',2052,N'客户科目分类'
EXEC [dbo].[InsertLocalizedLabel] 'Account','AccountClassificationCode',1033,N'Account Classification'
EXEC [dbo].[InsertLocalizedLabel] 'Account','AccountRatingCode',2052,N'客户等级'
EXEC [dbo].[InsertLocalizedLabel] 'Account','AccountRatingCode',1033,N'Account Rating'
EXEC [dbo].[InsertLocalizedLabel] 'Account','AccountNumber',2052,N'客户编号'
EXEC [dbo].[InsertLocalizedLabel] 'Account','AccountNumber',1033,N'Account Number' 
EXEC [dbo].[InsertLocalizedLabel] 'Account','BusinessTypeCode',2052,N'商业类型'
EXEC [dbo].[InsertLocalizedLabel] 'Account','BusinessTypeCode',1033,N'Business Type' 
EXEC [dbo].[InsertLocalizedLabel] 'Account','CustomerSizeCode',2052,N'客户大小'
EXEC [dbo].[InsertLocalizedLabel] 'Account','CustomerSizeCode',1033,N'Customer Size' 
EXEC [dbo].[InsertLocalizedLabel] 'Account','CustomerTypeCode',2052,N'关系类型'
EXEC [dbo].[InsertLocalizedLabel] 'Account','CustomerTypeCode',1033,N'Customer Type'
EXEC [dbo].[InsertLocalizedLabel] 'Account','OriginatingLeadId',2052,N'原始潜在顾客'
EXEC [dbo].[InsertLocalizedLabel] 'Account','OriginatingLeadId',1033,N'Originating Lead'
EXEC [dbo].[InsertLocalizedLabel] 'Account','CountryCode',2052,N'国家'
EXEC [dbo].[InsertLocalizedLabel] 'Account','CountryCode',1033,N'Country' 
EXEC [dbo].[InsertLocalizedLabel] 'Account','DepartmentId',2052,N'部门'
EXEC [dbo].[InsertLocalizedLabel] 'Account','DepartmentId',1033,N'Department' 

EXEC [dbo].[InsertLocalizedLabel] 'Contact','FullName',2052,N'全名'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','FullName',1033,N'FullName'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','EMailAddress1',2052,N'邮箱地址'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','EMailAddress1',1033,N'E-mail'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','ParentCustomerId',2052,N'上级客户'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','ParentCustomerId',1033,N'Parent Customer'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Telephone1',2052,N'业务电话'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Telephone1',1033,N'Parent Customer'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Fax',2052,N'传真'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Fax',1033,N'Fax'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','MobilePhone',2052,N'移动电话'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','MobilePhone',1033,N'Mobile Phone'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Telephone2',2052,N'家庭电话'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Telephone2',1033,N'Home Phone'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Description',1033,N'Description'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','AccountRoleCode',2052,N'客户角色'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','AccountRoleCode',1033,N'Account Role'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','JobTitle',2052,N'职位名称'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','JobTitle',1033,N'Job Title'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','EmployeeId',2052,N'员工编号'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','EmployeeId',1033,N'Employee Id'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','ManagerName',2052,N'经理'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','ManagerName',1033,N'Manager Name'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','AssistantName',2052,N'助理'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','AssistantName',1033,N'Assistant Name'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','ManangerPhone',2052,N'经理联系电话'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','ManangerPhone',1033,N'Mananger Phone'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','AssistantPhone',2052,N'助理联系电话'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','AssistantPhone',1033,N'Assistant Phone'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','GenderCode',2052,N'性别'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','GenderCode',1033,N'Gender'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','BirthDate',2052,N'出生日期'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','BirthDate',1033,N'Birth Date'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','EducationCode',2052,N'学历'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','EducationCode',1033,N'Education'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','OwnerId',2052,N'所有者'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','OwnerId',1033,N'Owner'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Department',2052,N'部门'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Department',1033,N'Department'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','OriginatingLeadId',2052,N'原始潜在顾客'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','OriginatingLeadId',1033,N'Originating Lead'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Anniversary',2052,N'纪念日'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Anniversary',1033,N'Anniversary'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','LastName',2052,N'姓氏'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','LastName',1033,N'LastName'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','FirstName',2052,N'名字'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','FirstName',1033,N'FirstName'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','MiddleName',2052,N''
EXEC [dbo].[InsertLocalizedLabel] 'Contact','MiddleName',1033,N'MiddleName'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','NickName',2052,N'昵称 '
EXEC [dbo].[InsertLocalizedLabel] 'Contact','NickName',1033,N'Nick Name'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','NumberOfChildren',2052,N'孩子数 '
EXEC [dbo].[InsertLocalizedLabel] 'Contact','NumberOfChildren',1033,N'Number Of Children' 
EXEC [dbo].[InsertLocalizedLabel] 'Contact','SpousesName',2052,N'配偶姓名 '
EXEC [dbo].[InsertLocalizedLabel] 'Contact','SpousesName',1033,N'Spouses Name'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','StatusCode',2052,N'状态'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','StatusCode',1033,N'Status'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Suffix',2052,N'称呼'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','Suffix',1033,N'Suffix' 
EXEC [dbo].[InsertLocalizedLabel] 'Contact','FamilyStatusCode',2052,N'婚姻状况'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','FamilyStatusCode',1033,N'Family Status' 
EXEC [dbo].[InsertLocalizedLabel] 'Contact','HasChildrenCode',2052,N'孩子情况'
EXEC [dbo].[InsertLocalizedLabel] 'Contact','HasChildrenCode',1033,N'Has Children'

EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','Name',2052,N'主题'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','Name',1033,N'Topic'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','CustomerId',2052,N'客户'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','CustomerId',1033,N'Potential Customer'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','OriginatingLeadId',2052,N'原始潜在顾客'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','OriginatingLeadId',1033,N'Originating Lead'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','EstimatedValue',2052,N'预计收入'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','EstimatedValue',1033,N'Estimated Revenue'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','TransactionCurrencyId',2052,N'货币'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','TransactionCurrencyId',1033,N'Currency'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','EstimatedCloseDate',2052,N'预计签约日期'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','EstimatedCloseDate',1033,N'Estimated Close Dated'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','CloseProbability',2052,N'可能性'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','CloseProbability',1033,N'Probability'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','PriorityCode',2052,N'优先级'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','PriorityCode',1033,N'Priority'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','OpportunityTypeCode',2052,N'机会类型'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','OpportunityTypeCode',1033,N'Opportunity Type'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','StepName',2052,N'下一步'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','StepName',1033,N'Next Step'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','OpportunityRatingCode',2052,N'机会等级'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','OpportunityRatingCode',1033,N'Opportunity Rating'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','SalesStageCode',2052,N'销售阶段'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','SalesStageCode',1033,N'Sales Stage'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','StatusCode',2052,N'状态'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','StatusCode',1033,N'Status'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','Description',1033,N'Description'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','DepartmentId',2052,N'部门'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','DepartmentId',1033,N'Department'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','OwnerId',2052,N'所有者'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','OwnerId',1033,N'Owner'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ProjectTypeCode',2052,N'项目类型'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ProjectTypeCode',1033,N'Project Type'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','TechnologyCode',2052,N'技术领域'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','TechnologyCode',1033,N'Technology'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','TechnicianId',2052,N'技术人员'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','TechnicianId',1033,N'Technician'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','LatestFeedbackOn',2052,N'最后反馈时间'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','LatestFeedbackOn',1033,N'Latest Feedback On'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ExpectedStartOn',2052,N'预计开始时间'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ExpectedStartOn',1033,N'Expected Start On'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','EstimatedWorkAmount',2052,N'工作量估计'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','EstimatedWorkAmount',1033,N'Estimated Work Amount'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ActualCloseDate',2052,N'实际关闭时间'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ActualCloseDate',1033,N'Actual Close Date'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ActualValue',2052,N'实际利润'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','ActualValue',1033,N'Actual Value'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','OpportunityId',2052,N'商业机遇'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','OpportunityId',1033,N'Opportunity ID'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','LeadSourceCode',2052,N'来源'
EXEC [dbo].[InsertLocalizedLabel] 'Opportunity','LeadSourceCode',1033,N'Lead Source'


EXEC [dbo].[InsertLocalizedLabel] 'Product','Name',2052,N'产品名称'
EXEC [dbo].[InsertLocalizedLabel] 'Product','Name',1033,N'Name'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ProductNumber',2052,N'产品编号'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ProductNumber',1033,N'Product Number'
EXEC [dbo].[InsertLocalizedLabel] 'Product','Price',2052,N'单价'
EXEC [dbo].[InsertLocalizedLabel] 'Product','Price',1033,N'Price'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ProductUrl',2052,N'产品链接'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ProductUrl',1033,N'Product URL'
EXEC [dbo].[InsertLocalizedLabel] 'Product','StandardCost',2052,N'标准成本'
EXEC [dbo].[InsertLocalizedLabel] 'Product','StandardCost',1033,N'Standard Cost'
EXEC [dbo].[InsertLocalizedLabel] 'Product','CurrentCost',2052,N'当前成本'
EXEC [dbo].[InsertLocalizedLabel] 'Product','CurrentCost',1033,N'Current　Cost'
EXEC [dbo].[InsertLocalizedLabel] 'Product','TransactionCurrencyId',2052,N'货币'
EXEC [dbo].[InsertLocalizedLabel] 'Product','TransactionCurrencyId',1033,N'Currency'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ExchangeRate',2052,N'汇率'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ExchangeRate',1033,N'ExchangeRate'
EXEC [dbo].[InsertLocalizedLabel] 'Product','StatusCode',2052,N'状态'
EXEC [dbo].[InsertLocalizedLabel] 'Product','StatusCode',1033,N'Status'
EXEC [dbo].[InsertLocalizedLabel] 'Product','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'Product','Description',1033,N'Description'
EXEC [dbo].[InsertLocalizedLabel] 'Product','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'Product','Description',1033,N'Description'
EXEC [dbo].[InsertLocalizedLabel] 'Product','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'Product','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'Product','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'Product','CreatedOn',1033,N'Created On' 
EXEC [dbo].[InsertLocalizedLabel] 'Product','ProductTypeCode',2052,N'产品类型'
EXEC [dbo].[InsertLocalizedLabel] 'Product','ProductTypeCode',1033,N'Product Type'

EXEC [dbo].[InsertLocalizedLabel] 'User','FullName',2052,N'姓  名'
EXEC [dbo].[InsertLocalizedLabel] 'User','FullName',1033,N'Full Name'
EXEC [dbo].[InsertLocalizedLabel] 'User','UserName',2052,N'用户名称'
EXEC [dbo].[InsertLocalizedLabel] 'User','UserName',1033,N'User Name'
EXEC [dbo].[InsertLocalizedLabel] 'User','EmailAddress',2052,N'邮箱'
EXEC [dbo].[InsertLocalizedLabel] 'User','EmailAddress',1033,N'Email Address'
EXEC [dbo].[InsertLocalizedLabel] 'User','ParentUserId',2052,N'经理'
EXEC [dbo].[InsertLocalizedLabel] 'User','ParentUserId',1033,N'Parent User Name'
EXEC [dbo].[InsertLocalizedLabel] 'User','MobilePhone',2052,N'移动电话'
EXEC [dbo].[InsertLocalizedLabel] 'User','MobilePhone',1033,N'Mobile Phone'
EXEC [dbo].[InsertLocalizedLabel] 'User','HomePhone',2052,N'家庭电话 '
EXEC [dbo].[InsertLocalizedLabel] 'User','HomePhone',1033,N'Home Phone'
EXEC [dbo].[InsertLocalizedLabel] 'User','NickName',2052,N'昵称 '
EXEC [dbo].[InsertLocalizedLabel] 'User','NickName',1033,N'Nick Name'
EXEC [dbo].[InsertLocalizedLabel] 'User','Password',2052,N'密码 '
EXEC [dbo].[InsertLocalizedLabel] 'User','Password',1033,N'Password'
EXEC [dbo].[InsertLocalizedLabel] 'User','FirstName',2052,N'名字 '
EXEC [dbo].[InsertLocalizedLabel] 'User','FirstName',1033,N'FirstName'
EXEC [dbo].[InsertLocalizedLabel] 'User','LastName',2052,N'姓氏 '
EXEC [dbo].[InsertLocalizedLabel] 'User','LastName',1033,N'LastName'
EXEC [dbo].[InsertLocalizedLabel] 'User','Title',2052,N'职称 '
EXEC [dbo].[InsertLocalizedLabel] 'User','Title',1033,N'Title'
EXEC [dbo].[InsertLocalizedLabel] 'User','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'User','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'User','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'User','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'User','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'User','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'User','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'User','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'User','MiddleName',2052,N''
EXEC [dbo].[InsertLocalizedLabel] 'User','MiddleName',1033,N'MiddleName'
EXEC [dbo].[InsertLocalizedLabel] 'User','DepartmentId',2052,N'部门'
EXEC [dbo].[InsertLocalizedLabel] 'User','DepartmentId',1033,N'Department'
EXEC [dbo].[InsertLocalizedLabel] 'User','NativePlace',2052,N'籍贯'
EXEC [dbo].[InsertLocalizedLabel] 'User','NativePlace',1033,N'Native Place'
EXEC [dbo].[InsertLocalizedLabel] 'User','EntryDate',2052,N'入职日期'
EXEC [dbo].[InsertLocalizedLabel] 'User','EntryDate',1033,N'Entry Date'
EXEC [dbo].[InsertLocalizedLabel] 'User','GraduatedCollege',2052,N'毕业院校'
EXEC [dbo].[InsertLocalizedLabel] 'User','GraduatedCollege',1033,N'Graduated College'
EXEC [dbo].[InsertLocalizedLabel] 'User','EnglishCommunication',2052,N'英语交流方式'
EXEC [dbo].[InsertLocalizedLabel] 'User','EnglishCommunication',1033,N'English Communication'
EXEC [dbo].[InsertLocalizedLabel] 'User','EnglishLevel',2052,N'英语等级'
EXEC [dbo].[InsertLocalizedLabel] 'User','EnglishLevel',1033,N'English Level'
EXEC [dbo].[InsertLocalizedLabel] 'User','TechnicalExpertise',2052,N'技术专长'
EXEC [dbo].[InsertLocalizedLabel] 'User','TechnicalExpertise',1033,N'Technical Expertise'
EXEC [dbo].[InsertLocalizedLabel] 'User','BirthDate',2052,N'生日'
EXEC [dbo].[InsertLocalizedLabel] 'User','BirthDate',1033,N'Birth Date'
EXEC [dbo].[InsertLocalizedLabel] 'User','MSN',2052,N'MSN'
EXEC [dbo].[InsertLocalizedLabel] 'User','MSN',1033,N'MSN'
EXEC [dbo].[InsertLocalizedLabel] 'User','QQ',2052,N'QQ'
EXEC [dbo].[InsertLocalizedLabel] 'User','QQ',1033,N'QQ'
EXEC [dbo].[InsertLocalizedLabel] 'User','Hobby',2052,N'个人爱好'
EXEC [dbo].[InsertLocalizedLabel] 'User','Hobby',1033,N'Hobby'
EXEC [dbo].[InsertLocalizedLabel] 'User','WorkExperience',2052,N'工作年限'
EXEC [dbo].[InsertLocalizedLabel] 'User','WorkExperience',1033,N'Work Experience'
EXEC [dbo].[InsertLocalizedLabel] 'User','JobLevelCode',2052,N'岗位级别'
EXEC [dbo].[InsertLocalizedLabel] 'User','JobLevelCode',1033,N'Job Level'
EXEC [dbo].[InsertLocalizedLabel] 'User','LastPromotionDate',2052,N'上次晋级日期'
EXEC [dbo].[InsertLocalizedLabel] 'User','LastPromotionDate',1033,N'Last Promotion Date'

EXEC [dbo].[InsertLocalizedLabel] 'Role','RoleName',2052,N'角色名'
EXEC [dbo].[InsertLocalizedLabel] 'Role','RoleName',1033,N'Role Name'
EXEC [dbo].[InsertLocalizedLabel] 'Role','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'Role','Description',1033,N'Description'


EXEC [dbo].[InsertLocalizedLabel] 'Contract','Title',2052,N'主题'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','Title',1033,N'Title'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ContractNumber',2052,N'合同编号'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ContractNumber',1033,N'ContractNumber'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','OpportunityId',2052,N'业务机遇'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','OpportunityId',1033,N'Opportunity'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','TotalPrice',2052,N'总价'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','TotalPrice',1033,N'TotalPrice'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','StatusCode',2052,N'状态'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','StatusCode',1033,N'Status'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ActiveOn',2052,N'起始时间'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ActiveOn',1033,N'Active On'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','CompanySignedOn',2052,N'我方签订时间'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','CompanySignedOn',1033,N'Company Signed On'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ExpiresOn',2052,N'期满失效'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ExpiresOn',1033,N'ExpiresOn'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','CustomerSignedOn',2052,N'客户签订时间'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','CustomerSignedOn',1033,N'Customer Signed On'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','BillingStartOn',2052,N'付款起始时间'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','BillingStartOn',1033,N'Billing Start On'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','BillingEndOn',2052,N'付款结束时间'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','BillingEndOn',1033,N'Billing End On'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','BillingCustomerId',2052,N'客户'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','BillingCustomerId',1033,N'Customer'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','BillingFrequencyCode',2052,N'记账频率'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','BillingFrequencyCode',1033,N'BillingFrequency'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','TransactionCurrencyId',2052,N'货币'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','TransactionCurrencyId',1033,N'Currency'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ExchangeRate',2052,N'汇率'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ExchangeRate',1033,N'ExchangeRate'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','Description',1033,N'Description'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','DepartmentId',2052,N'部门'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','DepartmentId',1033,N'Department'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','OwnerId',2052,N'所有者'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','OwnerId',1033,N'Owner'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','ModifiedOn',1033,N'Modified On' 
EXEC [dbo].[InsertLocalizedLabel] 'Contract','CustomerSatisfactionCode',2052,N'客户满意度'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','CustomerSatisfactionCode',1033,N'Customer Satisfaction'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','EndTypeCode',2052,N'项目结项方式'
EXEC [dbo].[InsertLocalizedLabel] 'Contract','EndTypeCode',1033,N'End Status' 

EXEC [dbo].[InsertLocalizedLabel] 'Audit','Action',2052,N'作用'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','Action',1033,N'Action'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','ObjectId',2052,N'对象'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','ObjectId',1033,N'Object'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','ObjectType',2052,N'模块'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','ObjectType',1033,N'Object Type'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','CreatedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','UserId',2052,N'操作人'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','UserId',1033,N'User'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','FieldName',2052,N'字段名称'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','FieldName',1033,N'Field Name'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','OriginalValue',2052,N'原始数据'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','OriginalValue',1033,N'Original Value'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','NewValue',2052,N'现在数据'
EXEC [dbo].[InsertLocalizedLabel] 'Audit','NewValue',1033,N'New Value'

EXEC [dbo].[InsertLocalizedLabel] 'TimeTracking','RecordById',2052,N'记录人'
EXEC [dbo].[InsertLocalizedLabel] 'TimeTracking','RecordById',1033,N'Record By Name'
EXEC [dbo].[InsertLocalizedLabel] 'TimeTracking','RecordOn',2052,N'记录时间'
EXEC [dbo].[InsertLocalizedLabel] 'TimeTracking','RecordOn',1033,N'Record On'
EXEC [dbo].[InsertLocalizedLabel] 'TimeTracking','TypeCode',2052,N'类型'
EXEC [dbo].[InsertLocalizedLabel] 'TimeTracking','TypeCode',1033,N'Type Code'
EXEC [dbo].[InsertLocalizedLabel] 'TimeTracking','Effort',2052,N'小时'
EXEC [dbo].[InsertLocalizedLabel] 'TimeTracking','Effort',1033,N'Effort'
EXEC [dbo].[InsertLocalizedLabel] 'TimeTracking','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'TimeTracking','Description',1033,N'Description'

EXEC [dbo].[InsertLocalizedLabel] 'CustomerAddress','Name',2052,N'帐单地址'
EXEC [dbo].[InsertLocalizedLabel] 'CustomerAddress','Name',1033,N'Billing Address'

EXEC [dbo].[InsertLocalizedLabel] 'Project','Name',2052,N'名称'
EXEC [dbo].[InsertLocalizedLabel] 'Project','Name',1033,N'Name'

EXEC [dbo].[InsertLocalizedLabel] 'Project','Objective',2052,N'目标'
EXEC [dbo].[InsertLocalizedLabel] 'Project','Objective',1033,N'Objective'

EXEC [dbo].[InsertLocalizedLabel] 'Project','PlannedStartDate',2052,N'合同开始日期'
EXEC [dbo].[InsertLocalizedLabel] 'Project','PlannedStartDate',1033,N'Panned Start Date'

EXEC [dbo].[InsertLocalizedLabel] 'Project','PlannedEndDate',2052,N'合同结束日期'
EXEC [dbo].[InsertLocalizedLabel] 'Project','PlannedEndDate',1033,N'Deadline'

EXEC [dbo].[InsertLocalizedLabel] 'Project','EstimatedEndDate',2052,N'预计结束日期'
EXEC [dbo].[InsertLocalizedLabel] 'Project','EstimatedEndDate',1033,N'Estimated End Date'

EXEC [dbo].[InsertLocalizedLabel] 'Project','PlannedProgress',2052,N'计划进度'
EXEC [dbo].[InsertLocalizedLabel] 'Project','PlannedProgress',1033,N'Planned Progress'

EXEC [dbo].[InsertLocalizedLabel] 'Project','ActualStartDate',2052,N'实际开始日期'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ActualStartDate',1033,N'Actual Start Date'

EXEC [dbo].[InsertLocalizedLabel] 'Project','ActualEndDate',2052,N'实际结束日期'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ActualEndDate',1033,N'Actual End Date'

EXEC [dbo].[InsertLocalizedLabel] 'Project','ActualProgress',2052,N'实际进度'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ActualProgress',1033,N'Actual End Date'

EXEC [dbo].[InsertLocalizedLabel] 'Project','ManagerId',2052,N'项目经理'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ManagerId',1033,N'Project Manager'

EXEC [dbo].[InsertLocalizedLabel] 'Project','StatusCode',2052,N'状态'
EXEC [dbo].[InsertLocalizedLabel] 'Project','StatusCode',1033,N'Status'

EXEC [dbo].[InsertLocalizedLabel] 'Project','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'Project','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'Project','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'Project','CreatedOn',1033,N'Created On'

EXEC [dbo].[InsertLocalizedLabel] 'Project','ContractId',2052,N'合同'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ContractId',1033,N'Contract'
EXEC [dbo].[InsertLocalizedLabel] 'Project','LatestFeadbackOn',2052,N'最后反馈时间'
EXEC [dbo].[InsertLocalizedLabel] 'Project','LatestFeadbackOn',1033,N'Latest Feedback On'

EXEC [dbo].[InsertLocalizedLabel] 'Project','CustomerId',2052,N'客户'
EXEC [dbo].[InsertLocalizedLabel] 'Project','CustomerId',1033,N'Potential Customer'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ProjectTypeCode',2052,N'项目类型'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ProjectTypeCode',1033,N'Project Type'
EXEC [dbo].[InsertLocalizedLabel] 'Project','TechnologyCode',2052,N'技术领域'
EXEC [dbo].[InsertLocalizedLabel] 'Project','TechnologyCode',1033,N'Technology'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ProbabilityCode',2052,N'后续可能性'
EXEC [dbo].[InsertLocalizedLabel] 'Project','ProbabilityCode',1033,N'Probability'

EXEC [dbo].[InsertLocalizedLabel] 'Project','Contact',2052,N'联系人'
EXEC [dbo].[InsertLocalizedLabel] 'Project','Contact',1033,N'Contact'

EXEC [dbo].[InsertLocalizedLabel] 'Project','SaleServiceId',2052,N'售后服务'
EXEC [dbo].[InsertLocalizedLabel] 'Project','SaleServiceId',1033,N'Sale Service'

--------------------------ProjectTask------------------------------
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','TaskId',2052,N'任务ID'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','TaskId',1033,N'TaskId'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','Name',2052,N'任务名称'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','Name',1033,N'Task Name'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ProjectId',2052,N'项目名称'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ProjectId',1033,N'Project Name'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ProjectIterationId',2052,N'迭代名称'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ProjectIterationId',1033,N'Iteration Name'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','StatusCode',2052,N'当前状态'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','StatusCode',1033,N'StatusCode'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','Description',1033,N'Description'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','QuoteWorkHours',2052,N'报价工时'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','QuoteWorkHours',1033,N'Quote Work Hours'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','PriorityCode',2052,N'优先级'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','PriorityCode',1033,N'Priority'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ActualWorkHours',2052,N'计划工时'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ActualWorkHours',1033,N'Actual Work Hours'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ActualInput',2052,N'实际投入'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ActualInput',1033,N'Actual Input'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','Effort',2052,N'有效产出'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','Effort',1033,N'Effort'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','Overtime',2052,N'加班产出'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','Overtime',1033,N'Over Time'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','OwnerId',2052,N'指派'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','OwnerId',1033,N'Assign To'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','EvaluateExactlyRate',2052,N'评估准确率'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','EvaluateExactlyRate',1033,N'Evaluate Exactly Rate'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','InputEffortRate',2052,N'投入产出比'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','InputEffortRate',1033,N'Input Effort Rate'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','RemainderTime',2052,N'剩余工作量'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','RemainderTime',1033,N'Remainder Time'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','StartDate',2052,N'开始日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','StartDate',1033,N'Start Date'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','EndDate',2052,N'结束日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','EndDate',1033,N'End Date'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','StartDate',2052,N'开始日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','StartDate',1033,N'Start Date'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','EndDate',2052,N'结束日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','EndDate',1033,N'End Date'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectTask','CreatedOn',1033,N'Created On'

---------------------ProjectIteration---------------
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','ProjectIterationId',2052,N'迭代ID'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','ProjectIterationId',1033,N'IterationId'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','ProjectId',2052,N'项目名称'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','ProjectId',1033,N'Project Name'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','Name',2052,N'迭代名称'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','Name',1033,N'Iteration Name'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','Objective',2052,N'目标'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','Objective',1033,N'Objective'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','StartDate',2052,N'开始日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','StartDate',1033,N'Start Date'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','Deadline',2052,N'结束日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','Deadline',1033,N'End Date'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','ProjectVersionId',2052,N'版本号'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','ProjectVersionId',1033,N'Version Number'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectIteration','CreatedOn',1033,N'Created On'

--------------------------------------ProjectWeekReport
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','ProjectWeekReportId',2052,N'项目周报ID'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','ProjectWeekReportId',1033,N'WeekReportId'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','Name',2052,N'周报名称'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','Name',1033,N'Name'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','ProjectId',2052,N'项目名称'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','ProjectId',1033,N'Project Name'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','ProjectIterationId',2052,N'迭代名称'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','ProjectIterationId',1033,N'Iteration Name'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CurrentProgressCode',2052,N'当前进度'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CurrentProgressCode',1033,N'Current Progress'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','OutlookProgressCode',2052,N'进度展望'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','OutlookProgressCode',1033,N'Outlook Progress'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CriteriaProgress',2052,N'进度评定'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CriteriaProgress',1033,N'Criteria Progress'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CurrentQualityCode',2052,N'当前质量'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CurrentQualityCode',1033,N'Current Quality'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','OutlookQualityCode',2052,N'质量展望'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','OutlookQualityCode',1033,N'Outlook Quality'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CriteriaQuality',2052,N'质量评定'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CriteriaQuality',1033,N'Criteria Quality'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','Suggestions',2052,N'问题&建议'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','Suggestions',1033,N'Issues&Suggestions'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','Reviews',2052,N'问题检讨'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','Reviews',1033,N'Reviews'

EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','RecordOn',2052,N'记录日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','RecordOn',1033,N'Record On'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','ModifiedById',1033,N'Modified By'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','ModifiedOn',2052,N'更新日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','ModifiedOn',1033,N'Modified On'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectWeekReport','CreatedOn',1033,N'Created On'

--------------------------------------Attendance
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','ModifiedOn',2052,N'修改日期'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','ModifiedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','ModifiedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','RecordOn',2052,N'记录日期'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','RecordOn',1033,N'Record On'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','RecordPersonId',2052,N'缺席人'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','RecordPersonId',1033,N'Record'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','AttendanceTypeCode',2052,N'缺席原因'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','AttendanceTypeCode',1033,N'Attendance Type Code'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','AttendanceLength',2052,N'缺席时间'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','AttendanceLength',1033,N'Attendance Length'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','AttendanceUnitCode',2052,N'时间单位'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','AttendanceUnitCode',1033,N'Attendance Unit Code'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'Attendance','Description',1033,N'Description'

--------------------------------------ProjectVersion
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','CreatedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','ModifiedOn',2052,N'修改日期'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','ModifiedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','ModifiedById',2052,N'修改人'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','ModifiedById',1033,N'Created By'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','VersionName',2052,N'版本号'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','VersionName',1033,N'Version Number'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','Description',2052,N'描述'
EXEC [dbo].[InsertLocalizedLabel] 'ProjectVersion','Description',1033,N'Description'

--------------------------------------AttentionInfomation
EXEC [dbo].[InsertLocalizedLabel] 'Notification','ObjectType',2052,N'类型'
EXEC [dbo].[InsertLocalizedLabel] 'Notification','ObjectType',1033,N'Record Type'
EXEC [dbo].[InsertLocalizedLabel] 'Notification','Subject',2052,N'主题'
EXEC [dbo].[InsertLocalizedLabel] 'Notification','Subject',1033,N'Subject'
EXEC [dbo].[InsertLocalizedLabel] 'Notification','Body',2052,N'内容'
EXEC [dbo].[InsertLocalizedLabel] 'Notification','Body',1033,N'Content'
EXEC [dbo].[InsertLocalizedLabel] 'Notification','CreatedOn',2052,N'创建日期'
EXEC [dbo].[InsertLocalizedLabel] 'Notification','CreatedOn',1033,N'Created On'
EXEC [dbo].[InsertLocalizedLabel] 'Notification','CreatedById',2052,N'创建人'
EXEC [dbo].[InsertLocalizedLabel] 'Notification','CreatedById',1033,N'Created By'
COMMIT
DROP PROCEDURE [dbo].[InsertLocalizedLabel] 
