   
 
 
 
 

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katrin.Domain    
{
    using System;
    public partial interface IDepartment : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid DepartmentId{ get;set;}
        string Name{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IOpportunity> Opportunities{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IContract> Contracts{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<ILead> Leads{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IUser> Users{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IAccount> Accounts{ get;set;}
    }
    
    public partial interface IOpportunity : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid OpportunityId{ get;set;}
        global::System.Nullable<global::System.Guid> DepartmentId{ get;set;}
        global::System.Nullable<global::System.Guid> CustomerId{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.Guid> OwnerId{ get;set;}
        global::System.Nullable<global::System.Guid> TechnicianId{ get;set;}
        global::System.Nullable<global::System.Guid> OriginatingLeadId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.Guid> TransactionCurrencyId{ get;set;}
        global::System.Nullable<double> EstimatedWorkAmount{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Nullable<global::System.Guid> StepId{ get;set;}
        global::System.Nullable<decimal> EstimatedValue{ get;set;}
        global::System.Nullable<decimal> ActualValue{ get;set;}
        global::System.Nullable<int> OpportunityTypeCode{ get;set;}
        string Name{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        global::System.Nullable<int> LeadSourceCode{ get;set;}
        global::System.Nullable<global::System.DateTime> ClosedTime{ get;set;}
        global::System.Nullable<global::System.DateTime> ActualCloseDate{ get;set;}
        int StatusCode{ get;set;}
        bool IsDeleted{ get;set;}
        global::System.Nullable<int> TechnologyCode{ get;set;}
        global::System.Nullable<int> SalesStageCode{ get;set;}
        global::System.Nullable<int> ProjectTypeCode{ get;set;}
        global::System.Nullable<int> OpportunityRatingCode{ get;set;}
        global::System.Nullable<global::System.DateTime> EstimatedCloseDate{ get;set;}
        global::System.Nullable<global::System.DateTime> ExpectedStartOn{ get;set;}
        global::System.Nullable<global::System.DateTime> LatestFeedbackOn{ get;set;}
        global::System.Nullable<int> PriorityCode{ get;set;}
        string StepName{ get;set;}
        string Description{ get;set;}
        global::System.Nullable<int> CloseProbability{ get;set;}
        IUser ModifiedBy{ get;set;}
        IAccount Customer{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IContract> Contracts{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IQuote> Quotes{ get;set;}
        ITransactionCurrency TransactionCurrency{ get;set;}
        IUser CreatedBy{ get;set;}
        IUser Technician{ get;set;}
        IUser Owner{ get;set;}
        IDepartment Department{ get;set;}
        ILead OriginatingLead{ get;set;}
    }
    
    public partial interface IUser : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid UserId{ get;set;}
        global::System.Nullable<global::System.Guid> DepartmentId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<bool> IsDisabled{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        string GraduatedCollege{ get;set;}
        string MSN{ get;set;}
        global::System.Nullable<global::System.DateTime> LastPromotionDate{ get;set;}
        string EnglishCommunication{ get;set;}
        string Hobby{ get;set;}
        string LastName{ get;set;}
        string WorkExperience{ get;set;}
        bool IsDeleted{ get;set;}
        string NativePlace{ get;set;}
        global::System.Nullable<int> JobLevelCode{ get;set;}
        string FirstName{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        string QQ{ get;set;}
        global::System.Nullable<int> UserType{ get;set;}
        global::System.Nullable<global::System.DateTime> EntryDate{ get;set;}
        string FullName{ get;set;}
        string PasswordSalt{ get;set;}
        string TechnicalExpertise{ get;set;}
        string MiddleName{ get;set;}
        global::System.Nullable<global::System.DateTime> BirthDate{ get;set;}
        string EnglishLevel{ get;set;}
        string EmailAddress{ get;set;}
        global::System.Nullable<global::System.Guid> ParentUserId{ get;set;}
        string Title{ get;set;}
        string Password{ get;set;}
        string MobilePhone{ get;set;}
        string NickName{ get;set;}
        string HomePhone{ get;set;}
        string UserName{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<INotification> Notifications{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IInvoice> Invoices{ get;set;}
        IUser ModifiedBy{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectMember> ProjectMembers{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IQuote> Quotes{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<INote> Notes{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IAccount> Accounts{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IContact> Contacts{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectTask> ProjectTasks{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IUserRole> UserRoles{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectWeekReport> ProjectWeekReports{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IAttendance> Attendances{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IOpportunity> Opportunities{ get;set;}
        IDepartment Department{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IUser> Users{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectIteration> ProjectIterations{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectVersion> ProjectVersions{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProject> Projects{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProduct> Products{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IContract> Contracts{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<ILead> Leads{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<ITimeTracking> TimeTrackings{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<INotificationRecipient> NotificationRecipients{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IAudit> Audits{ get;set;}
        IUser CreatedBy{ get;set;}
    }
    
    public partial interface INotification : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid NotificationId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> AboutAttributeId{ get;set;}
        string Body{ get;set;}
        string AboutUrl{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        string Subject{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        string NotificationUrl{ get;set;}
        string ObjectType{ get;set;}
        global::System.Nullable<global::System.Guid> ObjectId{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<INotificationRecipient> NotificationRecipients{ get;set;}
        IUser CreatedBy{ get;set;}
        IUser ModifiedBy{ get;set;}
    }
    
    public partial interface INotificationRecipient : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid NotificationRecipientId{ get;set;}
        global::System.Nullable<global::System.Guid> NotificationId{ get;set;}
        global::System.Nullable<global::System.Guid> RecipientId{ get;set;}
        string NotificationStatus{ get;set;}
        global::System.Nullable<global::System.DateTime> ReadedOn{ get;set;}
        INotification Notification{ get;set;}
        IUser Recipient{ get;set;}
    }
    
    public partial interface IInvoice : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid InvoiceId{ get;set;}
        global::System.Nullable<global::System.Guid> BillingCustomerId{ get;set;}
        global::System.Guid OwnerId{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        byte[] VersionNumber{ get;set;}
        bool IsDeleted{ get;set;}
        global::System.Nullable<global::System.DateTime> DateDelivered{ get;set;}
        string Name{ get;set;}
        string Description{ get;set;}
        global::System.Nullable<global::System.Guid> TransactionCurrencyId{ get;set;}
        int StatusCode{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        global::System.Nullable<decimal> TotalAmount{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Nullable<global::System.DateTime> ReceivedDate{ get;set;}
        string InvoiceNumber{ get;set;}
        global::System.Nullable<decimal> ExchangeRate{ get;set;}
        global::System.Nullable<decimal> PaidAmount{ get;set;}
        IUser Owner{ get;set;}
        IUser ModifiedBy{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IInvoiceContract> InvoiceContracts{ get;set;}
        IUser CreatedBy{ get;set;}
        IAccount BillingCustomer{ get;set;}
    }
    
    public partial interface IInvoiceContract : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid InvoiceContractId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Guid InvoiceId{ get;set;}
        global::System.Guid ContractId{ get;set;}
        IInvoice Invoice{ get;set;}
        IContract Contract{ get;set;}
    }
    
    public partial interface IContract : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid ContractId{ get;set;}
        global::System.Nullable<global::System.Guid> DepartmentId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Guid OwnerId{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> BillingCustomerId{ get;set;}
        global::System.Nullable<global::System.Guid> OpportunityId{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        string Description{ get;set;}
        string Title{ get;set;}
        global::System.Nullable<decimal> ExchangeRate{ get;set;}
        global::System.Nullable<global::System.DateTime> CompanySignedOn{ get;set;}
        global::System.Nullable<int> BillingFrequencyCode{ get;set;}
        bool IsDeleted{ get;set;}
        global::System.Nullable<global::System.Guid> TransactionCurrencyId{ get;set;}
        global::System.Nullable<int> EndTypeCode{ get;set;}
        global::System.Nullable<global::System.DateTime> BillingStartOn{ get;set;}
        global::System.Nullable<global::System.DateTime> ExpiresOn{ get;set;}
        global::System.Nullable<global::System.DateTime> BillingEndOn{ get;set;}
        global::System.Nullable<global::System.DateTime> CustomerSignedOn{ get;set;}
        global::System.Nullable<global::System.DateTime> CancelOn{ get;set;}
        string ContractNumber{ get;set;}
        global::System.Nullable<decimal> TotalPrice{ get;set;}
        global::System.Nullable<int> CustomerSatisfactionCode{ get;set;}
        int StatusCode{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Nullable<global::System.DateTime> ActiveOn{ get;set;}
        IUser Owner{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProject> Projects{ get;set;}
        IUser ModifiedBy{ get;set;}
        IDepartment Department{ get;set;}
        IAccount BillingCustomer{ get;set;}
        IOpportunity Opportunity{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IInvoiceContract> InvoiceContracts{ get;set;}
        IUser CreatedBy{ get;set;}
    }
    
    public partial interface IProject : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid ProjectId{ get;set;}
        global::System.Nullable<global::System.Guid> ContractId{ get;set;}
        global::System.Nullable<global::System.Guid> CustomerId{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> SaleServiceId{ get;set;}
        global::System.Nullable<global::System.Guid> ManagerId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.DateTime> PlannedStartDate{ get;set;}
        global::System.Nullable<global::System.DateTime> ActualEndDate{ get;set;}
        string Objective{ get;set;}
        global::System.Nullable<int> ProbabilityCode{ get;set;}
        global::System.Nullable<int> ProjectTypeCode{ get;set;}
        global::System.Nullable<global::System.DateTime> PlannedEndDate{ get;set;}
        global::System.Nullable<int> TechnologyCode{ get;set;}
        global::System.Nullable<global::System.DateTime> LatestFeadbackOn{ get;set;}
        string Contact{ get;set;}
        global::System.Nullable<int> PlannedProgress{ get;set;}
        global::System.Nullable<global::System.DateTime> EstimatedEndDate{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        string Name{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        int StatusCode{ get;set;}
        global::System.Nullable<global::System.DateTime> ActualStartDate{ get;set;}
        bool IsDeleted{ get;set;}
        global::System.Nullable<int> ActualProgress{ get;set;}
        IUser Manager{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectIteration> ProjectIterations{ get;set;}
        IUser ModifiedBy{ get;set;}
        IUser CreatedBy{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectWeekReport> ProjectWeekReports{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectMember> ProjectMembers{ get;set;}
        IContract Contract{ get;set;}
        IUser SaleService{ get;set;}
        IAccount Customer{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectVersion> ProjectVersions{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectTask> ProjectTasks{ get;set;}
    }
    
    public partial interface IProjectIteration : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid ProjectIterationId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.Guid> ProjectVersionId{ get;set;}
        global::System.Guid ProjectId{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        bool IsDeleted{ get;set;}
        string Objective{ get;set;}
        string Name{ get;set;}
        global::System.Nullable<global::System.DateTime> StartDate{ get;set;}
        global::System.Nullable<global::System.DateTime> Deadline{ get;set;}
        IProjectVersion ProjectVersion{ get;set;}
        IProject Project{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectWeekReport> ProjectWeekReports{ get;set;}
        IUser CreatedBy{ get;set;}
        IUser ModifiedBy{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectTask> ProjectTasks{ get;set;}
    }
    
    public partial interface IProjectVersion : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid ProjectVersionId{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Guid ProjectId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        string VersionName{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        string Description{ get;set;}
        bool IsDeleted{ get;set;}
        IUser ModifiedBy{ get;set;}
        IUser CreatedBy{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProjectIteration> ProjectIterations{ get;set;}
        IProject Project{ get;set;}
    }
    
    public partial interface IProjectWeekReport : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid ProjectWeekReportId{ get;set;}
        global::System.Guid ProjectIterationId{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Guid ProjectId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<int> OutlookProgressCode{ get;set;}
        global::System.Nullable<int> CurrentProgressCode{ get;set;}
        global::System.Nullable<global::System.DateTime> RecordOn{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        global::System.Nullable<int> OutlookQualityCode{ get;set;}
        string Reviews{ get;set;}
        string Name{ get;set;}
        string CriteriaQuality{ get;set;}
        global::System.Nullable<int> CurrentQualityCode{ get;set;}
        string Suggestions{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        string CriteriaProgress{ get;set;}
        IProject Project{ get;set;}
        IProjectIteration ProjectIteration{ get;set;}
        IUser ModifiedBy{ get;set;}
        IUser CreatedBy{ get;set;}
    }
    
    public partial interface IProjectTask : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid TaskId{ get;set;}
        global::System.Nullable<global::System.Guid> ProjectIterationId{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> OwnerId{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Guid ProjectId{ get;set;}
        global::System.Nullable<double> Effort{ get;set;}
        bool IsDeleted{ get;set;}
        string Description{ get;set;}
        global::System.Nullable<double> EvaluateExactlyRate{ get;set;}
        global::System.Nullable<double> ActualWorkHours{ get;set;}
        global::System.Nullable<int> PriorityCode{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Nullable<double> Overtime{ get;set;}
        global::System.Nullable<double> RemainderTime{ get;set;}
        global::System.Nullable<double> QuoteWorkHours{ get;set;}
        global::System.Nullable<double> ActualInput{ get;set;}
        int StatusCode{ get;set;}
        global::System.Nullable<double> InputEffortRate{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        global::System.Nullable<global::System.DateTime> EndDate{ get;set;}
        global::System.Nullable<global::System.DateTime> StartDate{ get;set;}
        string Name{ get;set;}
        IUser ModifiedBy{ get;set;}
        IUser CreatedBy{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<ITaskTimeHistory> TaskTimeHistories{ get;set;}
        IProject Project{ get;set;}
        IProjectIteration ProjectIteration{ get;set;}
        IUser Owner{ get;set;}
    }
    
    public partial interface ITaskTimeHistory : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid TaskTimeHistoryId{ get;set;}
        global::System.Guid TaskId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        global::System.Nullable<double> Effort{ get;set;}
        global::System.Nullable<double> ActualInput{ get;set;}
        global::System.Nullable<double> ActualProgress{ get;set;}
        global::System.Nullable<int> EndTime{ get;set;}
        global::System.Nullable<int> StartTime{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        string Description{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.DateTime> RecordOn{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<double> Overtime{ get;set;}
        bool IsDeleted{ get;set;}
        IProjectTask Task{ get;set;}
    }
    
    public partial interface IProjectMember : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid ProjectMemberId{ get;set;}
        global::System.Guid ProjectId{ get;set;}
        global::System.Guid MemberId{ get;set;}
        IProject Project{ get;set;}
        IUser Member{ get;set;}
    }
    
    public partial interface IAccount : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid AccountId{ get;set;}
        global::System.Nullable<global::System.Guid> DepartmentId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Guid OwnerId{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.Guid> PrimaryContactId{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        string Telephone1{ get;set;}
        global::System.Nullable<int> CountryCode{ get;set;}
        bool IsDeleted{ get;set;}
        int StatusCode{ get;set;}
        string Name{ get;set;}
        string Country{ get;set;}
        global::System.Nullable<int> IndustryCode{ get;set;}
        global::System.Nullable<int> CustomerSizeCode{ get;set;}
        string Telephone2{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        global::System.Nullable<int> NumberOfEmployees{ get;set;}
        global::System.Nullable<int> PaymentTermsCode{ get;set;}
        string WebSiteURL{ get;set;}
        string EMailAddress1{ get;set;}
        global::System.Nullable<int> AccountCategoryCode{ get;set;}
        global::System.Nullable<int> AccountClassificationCode{ get;set;}
        string SIC{ get;set;}
        string Telephone3{ get;set;}
        global::System.Nullable<int> BusinessTypeCode{ get;set;}
        string EMailAddress3{ get;set;}
        string City{ get;set;}
        global::System.Nullable<int> OwnershipCode{ get;set;}
        global::System.Nullable<int> CustomerTypeCode{ get;set;}
        string AccountNumber{ get;set;}
        global::System.Nullable<int> AccountRatingCode{ get;set;}
        global::System.Nullable<global::System.Guid> ParentAccountId{ get;set;}
        global::System.Nullable<decimal> Revenue{ get;set;}
        global::System.Nullable<global::System.Guid> OriginatingLeadId{ get;set;}
        string EMailAddress2{ get;set;}
        string Description{ get;set;}
        string TickerSymbol{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        IUser Owner{ get;set;}
        IUser CreatedBy{ get;set;}
        IDepartment Department{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IContract> Contracts{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IProject> Projects{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IOpportunity> Opportunities{ get;set;}
        IContact PrimaryContact{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IQuote> Quotes{ get;set;}
        IUser ModifiedBy{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IInvoice> Invoices{ get;set;}
    }
    
    public partial interface IContact : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid ContactId{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<int> EducationCode{ get;set;}
        string FirstName{ get;set;}
        int StatusCode{ get;set;}
        string MobilePhone{ get;set;}
        string Telephone2{ get;set;}
        global::System.Nullable<global::System.Guid> OriginatingLeadId{ get;set;}
        string Telephone3{ get;set;}
        global::System.Nullable<int> HasChildrenCode{ get;set;}
        string SpousesName{ get;set;}
        string JobTitle{ get;set;}
        string EMailAddress1{ get;set;}
        global::System.Nullable<int> NumberOfChildren{ get;set;}
        string Suffix{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Guid OwnerId{ get;set;}
        bool IsDeleted{ get;set;}
        string AssistantName{ get;set;}
        string ManangerPhone{ get;set;}
        global::System.Nullable<int> FamilyStatusCode{ get;set;}
        global::System.Nullable<decimal> AnnualIncome{ get;set;}
        string EMailAddress3{ get;set;}
        string NickName{ get;set;}
        string Fax{ get;set;}
        global::System.Nullable<global::System.Guid> ParentCustomerId{ get;set;}
        string Department{ get;set;}
        string EMailAddress2{ get;set;}
        string Description{ get;set;}
        string LastName{ get;set;}
        global::System.Nullable<int> AccountRoleCode{ get;set;}
        string AssistantPhone{ get;set;}
        string Telephone1{ get;set;}
        string MiddleName{ get;set;}
        global::System.Nullable<int> GenderCode{ get;set;}
        string ManagerName{ get;set;}
        string WebSiteUrl{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        string EmployeeId{ get;set;}
        global::System.Nullable<global::System.DateTime> Anniversary{ get;set;}
        global::System.Nullable<global::System.DateTime> BirthDate{ get;set;}
        string FullName{ get;set;}
        IUser CreatedBy{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IAccount> Accounts{ get;set;}
        IUser ModifiedBy{ get;set;}
    }
    
    public partial interface IQuote : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid QuoteId{ get;set;}
        global::System.Nullable<global::System.Guid> CustomerId{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> OwnerId{ get;set;}
        global::System.Nullable<global::System.Guid> OpportunityId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.Guid> BillTo_AddressId{ get;set;}
        global::System.Nullable<decimal> TotalLineItemAmount{ get;set;}
        string Description{ get;set;}
        global::System.Nullable<global::System.Guid> TransactionCurrencyId{ get;set;}
        global::System.Nullable<int> StageCode{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Nullable<global::System.DateTime> ExpiresOn{ get;set;}
        global::System.Nullable<decimal> TotalAmount{ get;set;}
        global::System.Nullable<decimal> TotalTax{ get;set;}
        global::System.Nullable<decimal> TotalDiscountAmount{ get;set;}
        string Name{ get;set;}
        global::System.Nullable<int> PaymentTermsCode{ get;set;}
        string BillTo_ContactName{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        global::System.Nullable<decimal> ExchangeRate{ get;set;}
        int StatusCode{ get;set;}
        string QuoteNumber{ get;set;}
        bool IsDeleted{ get;set;}
        IUser ModifiedBy{ get;set;}
        ICustomerAddress BillTo_Address{ get;set;}
        IOpportunity Opportunity{ get;set;}
        IAccount Customer{ get;set;}
        IUser Owner{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IQuoteLineItem> QuoteLineItems{ get;set;}
        IUser CreatedBy{ get;set;}
    }
    
    public partial interface ICustomerAddress : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid CustomerAddressId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<int> AddressTypeCode{ get;set;}
        string Country{ get;set;}
        string PrimaryContactName{ get;set;}
        global::System.Nullable<double> Latitude{ get;set;}
        string Line2{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        string PostOfficeBox{ get;set;}
        global::System.Nullable<int> PostalCode{ get;set;}
        string Line3{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        bool IsDeleted{ get;set;}
        string Name{ get;set;}
        string County{ get;set;}
        string Fax{ get;set;}
        string City{ get;set;}
        global::System.Nullable<double> Longitude{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Nullable<global::System.Guid> ParentId{ get;set;}
        string Line1{ get;set;}
        string StateOrProvince{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IQuote> Quotes{ get;set;}
    }
    
    public partial interface IQuoteLineItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid QuoteLineItemId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.Guid> QuoteId{ get;set;}
        global::System.Nullable<decimal> TotalPrice{ get;set;}
        global::System.Nullable<decimal> Quantity{ get;set;}
        global::System.Nullable<decimal> UnitPrice{ get;set;}
        global::System.Nullable<global::System.Guid> ProductId{ get;set;}
        IQuote Quote{ get;set;}
    }
    
    public partial interface INote : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid NoteId{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        byte[] VersionNumber{ get;set;}
        string ObjectType{ get;set;}
        global::System.Nullable<global::System.Guid> ObjectId{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        string NoteText{ get;set;}
        bool IsDeleted{ get;set;}
        string Subject{ get;set;}
        IUser ModifiedBy{ get;set;}
        IUser CreatedBy{ get;set;}
    }
    
    public partial interface IUserRole : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid Id{ get;set;}
        global::System.Nullable<global::System.Guid> RoleId{ get;set;}
        global::System.Nullable<global::System.Guid> UserId{ get;set;}
        IRole Role{ get;set;}
        IUser User{ get;set;}
    }
    
    public partial interface IRole : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid RoleId{ get;set;}
        string RoleName{ get;set;}
        string Description{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IRolePrivilege> RolePrivileges{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IUserRole> UserRoles{ get;set;}
    }
    
    public partial interface IRolePrivilege : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid RolePrivilegeId{ get;set;}
        global::System.Guid PrivilegeId{ get;set;}
        global::System.Guid RoleId{ get;set;}
        IPrivilege Privilege{ get;set;}
        IRole Role{ get;set;}
    }
    
    public partial interface IPrivilege : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid PrivilegeId{ get;set;}
        string Name{ get;set;}
        global::System.Nullable<int> AccessRight{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IRolePrivilege> RolePrivileges{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IPrivilegeEntity> PrivilegeEntities{ get;set;}
    }
    
    public partial interface IPrivilegeEntity : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid PrivilegeEntityId{ get;set;}
        global::System.Guid PrivilegeId{ get;set;}
        string EntityName{ get;set;}
        IPrivilege Privilege{ get;set;}
    }
    
    public partial interface IAttendance : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid AttendanceId{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.Guid> RecordPersonId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        string Description{ get;set;}
        global::System.Nullable<int> AttendanceUnitCode{ get;set;}
        bool IsDeleted{ get;set;}
        global::System.Nullable<int> AttendanceTypeCode{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Nullable<global::System.DateTime> RecordOn{ get;set;}
        global::System.Nullable<int> AttendanceLength{ get;set;}
        IUser ModifiedBy{ get;set;}
        IUser RecordPerson{ get;set;}
        IUser CreatedBy{ get;set;}
    }
    
    public partial interface IProduct : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid ProductId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<decimal> Price{ get;set;}
        global::System.Nullable<decimal> CurrentCost{ get;set;}
        bool IsDeleted{ get;set;}
        string Description{ get;set;}
        global::System.Nullable<int> ProductTypeCode{ get;set;}
        string Name{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        global::System.Nullable<global::System.Guid> TransactionCurrencyId{ get;set;}
        string ProductNumber{ get;set;}
        global::System.Nullable<decimal> StandardCost{ get;set;}
        string ProductUrl{ get;set;}
        global::System.Nullable<decimal> ExchangeRate{ get;set;}
        int StatusCode{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        IUser CreatedBy{ get;set;}
        IUser ModifiedBy{ get;set;}
    }
    
    public partial interface ILead : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid LeadId{ get;set;}
        global::System.Nullable<global::System.Guid> DepartmentId{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        global::System.Nullable<global::System.Guid> OwnerId{ get;set;}
        byte[] VersionNumber{ get;set;}
        string WebSiteUrl{ get;set;}
        string Fax{ get;set;}
        bool IsDeleted{ get;set;}
        string MiddleName{ get;set;}
        string Address{ get;set;}
        string FullName{ get;set;}
        string Telephone2{ get;set;}
        int StatusCode{ get;set;}
        string Subject{ get;set;}
        string Telephone1{ get;set;}
        string LastName{ get;set;}
        global::System.Nullable<decimal> Revenue{ get;set;}
        string MobilePhone{ get;set;}
        string City{ get;set;}
        global::System.Nullable<int> TechnologyCode{ get;set;}
        string OriginalMessage{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        string Country{ get;set;}
        global::System.Nullable<int> LeadSourceCode{ get;set;}
        global::System.Nullable<int> CountryCode{ get;set;}
        string Description{ get;set;}
        string CompanyName{ get;set;}
        string ZIP{ get;set;}
        global::System.Nullable<global::System.Guid> CustomerId{ get;set;}
        string NumberOfEmployees{ get;set;}
        string FirstName{ get;set;}
        global::System.Nullable<int> PriorityCode{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        string EmailAddress{ get;set;}
        IUser ModifiedBy{ get;set;}
        IUser CreatedBy{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IOpportunity> Opportunities{ get;set;}
        IUser Owner{ get;set;}
        IDepartment Department{ get;set;}
    }
    
    public partial interface ITimeTracking : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid TimeTrackingId{ get;set;}
        global::System.Nullable<global::System.Guid> RecordById{ get;set;}
        global::System.Nullable<global::System.DateTime> RecordOn{ get;set;}
        global::System.Nullable<global::System.Guid> OpportunityId{ get;set;}
        global::System.Nullable<int> TypeCode{ get;set;}
        string Description{ get;set;}
        global::System.Nullable<double> Effort{ get;set;}
        IUser RecordBy{ get;set;}
    }
    
    public partial interface IAudit : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid AuditId{ get;set;}
        global::System.Nullable<global::System.Guid> UserId{ get;set;}
        string Action{ get;set;}
        global::System.Nullable<global::System.Guid> ObjectId{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Guid TrasactionId{ get;set;}
        string FieldName{ get;set;}
        string ChangeDate{ get;set;}
        string ObjectType{ get;set;}
        string NewValue{ get;set;}
        string OriginalValue{ get;set;}
        IUser User{ get;set;}
    }
    
    public partial interface ITransactionCurrency : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid TransactionCurrencyId{ get;set;}
        byte[] VersionNumber{ get;set;}
        global::System.Nullable<global::System.DateTime> CreatedOn{ get;set;}
        global::System.Nullable<global::System.DateTime> ModifiedOn{ get;set;}
        bool IsDeleted{ get;set;}
        string CurrencyName{ get;set;}
        string CurrencySymbol{ get;set;}
        global::System.Nullable<decimal> ExchangeRate{ get;set;}
        global::System.Nullable<global::System.Guid> CreatedById{ get;set;}
        int CurrencyPrecision{ get;set;}
        global::System.Nullable<global::System.Guid> ModifiedById{ get;set;}
        int StatusCode{ get;set;}
        global::System.Data.Services.Client.DataServiceCollection<IOpportunity> Opportunities{ get;set;}
    }
    
    public partial interface ISystemSetting : global::System.ComponentModel.INotifyPropertyChanged
    {
        global::System.Guid SystemSettingId{ get;set;}
        string Name{ get;set;}
        string Value{ get;set;}
    }
    
}
    
